### ISSUE TITLE
Add support for ListItem underlayColor

### ISSUE THREAD

**Issue by jacobsmith** [react-native-training/react-native-elements#1842] opened 2019-03-25 14:53 UTC
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
I added the `underlayColor` option to a ListItem. Because I am using the `onPress` function, `react-native-elements` renders a `TouchableHighlight` for the component, but `underlayColor` is not an exposed property in the type signature.

**Expected behaviour**
I expect to be able to add `underlayColor` to a ListItem when it is rendering as a `TouchableHighlight` (or any other component that accepts an `underlayColor` attribute).

**Describe the bug**
I see a type error, but the code itself executes fine. The bug is only in what appears to be inconsistent typings.

**Possible Solution**
I believe there is a way with TypeScript to allow that property if and only if the underlying component supports it, but I'm not quite sure how to tackle that. @iRoachie mentioned he may be able to help guide me through the type annotations.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |     1.0.0    |
| react-native          |   https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz      |
| npm or yarn           |    yarn     |

**Comment by iRoachie** [comment] 2019-04-18 06:26
Hey @jacobsmith, The problem is that ListItemProps doesn't have an `underlayColor` prop https://github.com/react-native-training/react-native-elements/blob/master/src/index.d.ts#L1118.

`underlayColor` in a part of the TouchableHighlightProps from react-native. To get that prop we should extend from that interface.

```ts
// Before
export interface ListItemProps { }

// After
export interface ListItemProps extends TouchableHighlightProps { }
```

**Comment by betoharres** [comment] 2019-06-11 20:42
Something similar happened to me, my configuration of the RNE ThemeProvider looked like this:
```
  const rneTheme = {
    ListItem: {
      borderTopWidth: 0.3,
      borderBottomWidth: 0.3,
      borderColor: theme.colors.grey,
      titleStyle: {
           ...
      },
      subtitleStyle: {
          ....
      },
    },
  }
```
While this works and the border shows, I had a problem that the border dissapered when adding a custom function to the prop `onPress`.
So in order to work I just needed to wrap the border attributes inside a `containerStyles` attribute.

**Comment by iRoachie** [comment] 2019-07-14 19:57
Just merged in a fix for this. Will be available in 1.2.0

**Closed by iRoachie** 2019-07-14 19:57 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release, 🗂 Types

**Comment by lehtaku** [comment] 2019-11-24 12:09
@iRoachie 

I still didn't find a way to change ListItem underlay color. I'm using react-native-elements 1.2.7.

**Comment by iRoachie** [comment] 2019-11-24 13:20
Just set `underlayColor` prop https://snack.expo.io/@roach_iam/honest-salsa

**Comment by dan640** [comment] 2021-02-13 17:57
Hi @iRoachie. I tried to use margin on a ListItem and it seems that the underlay color is also visible in the margin area. Is this intended? If I set it to white, then the ListItem doesn't change color on an onPress event. Is there a way to solve this?
https://snack.expo.io/Q9AbtGp4Y

**Comment by iRoachie** [comment] 2021-02-17 13:45
@dan640 just use the `style` attribute instead of `containerStyle`. `style` gets passed to the outer container. https://github.com/react-native-elements/react-native-elements/blob/next/src/list/ListItem.js#L41
