### ISSUE TITLE
Input element broken

### ISSUE THREAD

**Issue by pensivej** [react-native-training/react-native-elements#1155] opened 2018-04-29 21:12 UTC
### Description

1. Explain what you did

I just simply added basic input, following the tutorial but it crashes.

2. What you expected to happen

Just a simple input testing

3. What actually happens

Invariant violation: Element type is invalid

Also please include the version of `react-native-elements` that you are using.

0.18.5

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

https://snack.expo.io/rk3sNhQTG

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by Craques** [comment] 2018-04-30 00:04
I think the Input element is available in the beta. If you run npm i --save react-native-elements@beta

**Comment by pensivej** [comment] 2018-04-30 00:05
yes, I noticed.

Others, for current version (0.18.5) use FormInput instead of Input

**Comment by xavier-villelegier** [comment] 2018-04-30 02:49
Duplicate of #1154 #1099 #1025 and others

**Closed by xavier-villelegier** 2018-04-30 02:49 UTC
