### ISSUE TITLE
RNE x RNW, Button is not clickable and mysterious red border appears

### ISSUE THREAD

**Issue by haruelrovix** [react-native-training/react-native-elements#1450] opened 2018-10-08 11:35 UTC
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
Render RNE Button using [React Native Web](https://github.com/necolas/react-native-web).

**Expected behaviour**
RNE Button should be clickable WITHOUT red border there.

**Describe the bug**
RNE Button works perfectly on Native, tested on Android. It's clickable and there is no issue with the style.
However, the RNW version of it can't be clicked and there is Red border outside.

**To Reproduce**

# Steps
1. Clone this repository: [rnw-github](https://github.com/haruelrovix/rnw-github.git)
`$ git clone https://github.com/haruelrovix/rnw-github.git && cd rnw-github`
2. Change to branch `rne-button-issue`
`$ git checkout rne-button-issue`
3. Install package dependencies.
`$ yarn`

4. Run `yarn android`. Make sure you have connected device.
<img src="https://user-images.githubusercontent.com/17120764/46603258-c639ce00-cb1c-11e8-9e43-b10c1a9b120b.png" width=200 />

5. Run `yarn web`.

<img src="https://user-images.githubusercontent.com/17120764/46606569-d6a37600-cb27-11e8-9b29-fc09662e2dd6.png" width=250>

**Possible Solution**
RN Button has no issue. So it must be something inside RNE Button. Currently I use `Button.web.js` for the workaround, to achieve similar look and feel for Web. [Code](https://github.com/haruelrovix/rnw-github/pull/1/files#diff-ce10cc60314c8ec301157b4f4b385b23).

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements |`1.0.0-beta5` |
| react-native |`0.55.4` |
| npm or yarn |`v1.9.4` |

**Comment by iRoachie** [comment] 2018-10-08 11:40
This should be solved by https://github.com/react-native-training/react-native-elements/pull/1421. The problem is that TouchableNativeFeedback is not available on web https://github.com/react-native-training/react-native-elements/blob/master/src/buttons/Button.js#L164

**Comment by iRoachie** [comment] 2018-12-06 05:15
Fixed by https://github.com/react-native-training/react-native-elements/commit/659ad08dbeee0ebd1cb7e14b2c9819abf9400d05

**Closed** 2018-12-06 05:15 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release
