### ISSUE TITLE
Setting custom Button background color in ThemeProvider breaks Clear button type

### ISSUE THREAD

**Issue by dquessenberry** [react-native-training/react-native-elements#1972] opened 2019-07-20 20:31 UTC
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).
RNE v1.1.0

**Explain what you did**
What you were trying to accomplish.

I am using a custom ThemeProvider where I set buttons' background and text to custom colors (black/white respectively), however in the instances where I want to generate an icon button, I would prefer the reverse.

**Expected behaviour**

By default, RNE Buttons have a blue background with white text, and if I set the button type to "clear", then background renders as transparent. However this is not the case if I set the button style background color to a custom color in my ThemeProvider. So basically setting the button style background color in the ThemeProvider breaks the concept of "clear" buttons. I would expect that when a button's type is set to "clear", then a transparent background color would override any custom default color.

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

Set button background color in ThemeProvider to any color:

> // ThemeProvider config
> const Theme = {
>   Button: {
>     buttonStyle: {
>       backgroundColor: ''#000
>     }
>  },
>   ...
> }
> 
> 
> // Use of a button
> &lt;Button type="clear" title="Clear Test" /&gt;  // renders transparent background when no background color is set in ThemeProvider, but does not render a transparent background if you do set a background color in ThemeProvider
> 
> &lt;Button title="Default Test" /&gt; // renders a solid background 

**Possible Solution**
Can you suggest a possible fix that would address this issue?

Alway overrider any set background color to transparent if a button type is set to "clear". Or better yet, support specific styling configuration in a ThemeProvider for "clear" type buttons.

| software              | version |
| --------------------- | ------- |
| react-native-elements |  1.1.0  |
| react-native          |  0.59.9  |
| npm           |  6.9.0  |

**Comment by iRoachie** [comment] 2019-07-27 13:31
Duplicate of #1886

**Closed by iRoachie** 2019-07-27 13:31 UTC
