### ISSUE TITLE
CheckBox needs a props <numberOfLines> for title Text component

### ISSUE THREAD

**Issue by softdev999** [react-native-training/react-native-elements#1273] opened 2018-06-20 17:47 UTC
Hi, 

The CheckBox from react-native-elements is really looking good.
But I think we need to have one more props for title text.

For example, 
Currently, the title in CheckBox doesn't support numberOfLines

![image](https://user-images.githubusercontent.com/17640308/41675160-885238e4-74f4-11e8-99f7-6145bfe7388a.png)

But we need the title ellipse truncated like this

![image](https://user-images.githubusercontent.com/17640308/41675210-a55e7466-74f4-11e8-857a-e4a01a616ce0.png)

Now, this can be done by adding one line into CheckBox.js in the installed node_modules folder like this.

![image](https://user-images.githubusercontent.com/17640308/41675262-ca087820-74f4-11e8-9913-42b3d1371edd.png)

But I think this is not a right way because it's not happy to touch the installed node_modules as you know...

Would you please add a <numberOfLines> as props of CheckBox for this purpose?
I think it's not difficult to achieve this, thus we hope you will update your repo very soon.

My best,
Thanks

**Comment by iRoachie** [comment] 2018-06-20 20:19
Hey! Can you let me know what version of react-native-elements you’re using?

**Comment by softdev999** [comment] 2018-06-21 03:30
Hi, I installed the package using npm install yesterday, it should be the latest one then?

Anyhow, I attached my package.json

![image](https://user-images.githubusercontent.com/17640308/41696400-7d741814-7546-11e8-8472-6203d3199345.png)

Thank you

**Comment by iRoachie** [comment] 2018-06-22 03:18
Hey @softdev999, thanks for bringing that up. Right now any new features we add will be released into the `beta` version of react-native-elements. That being said, would you be willing to create the PR that would enable this functionality? If so, remember to create your PR based on `next` and **not** `master`.

Instead of just creating a `numberOfLines` prop to pass in, it might be better to have a `titleProps` prop so the user can pass in any props they need to the Text component.

**Comment by softdev999** [comment] 2018-06-25 11:51
Thanks for your reply, so, you mean I need to change node_modules installed?
I think it's not good, we hope you would update your repo with that titleProps and allow us to pull soon.

Again, many thanks
Best,

**Comment by kirakik** [comment] 2018-07-14 19:37
Hi @softdev999, I believe what @iRoachie meant is that if you could, to help contribute back to the project by opening a Pull Request with the suggested fix, not editing the logic in your `node_modules`.

I took a look at the issue and [could not reproduce it](https://snack.expo.io/r1Upl0vm7), could you share with us the code you used to render the Checkbox, and any styles that you overwrote using the props?

**Comment by iRoachie** [comment] 2019-02-06 03:04
Just implemented in https://github.com/react-native-training/react-native-elements/pull/1757.

You'll be able to pass in all props from the Text component:

```jsx

<CheckBox title="Yea" titleProps={{ numberOfLines:  2}} />
```

**Closed** 2019-02-06 03:04 UTC
Labels: Good First Issue, ✅ Fixed - Next Release, ✨Enhancement
