### ISSUE TITLE
ListItem renders unwanted vertical white-space that I cannot control

### ISSUE THREAD

**Issue by lsiden** [react-native-training/react-native-elements#1138] opened 2018-04-24 19:14 UTC
On v1.0.0-beta4, ListItem renders vertical padding above and below its contents that I cannot get rid of.  When I examine this on Android with the inspector, it does not show any value for padding, but there is nevertheless white-space above and below the text that I cannot adjust.  This was not the case with v0.19.x.

**Comment by xavier-villelegier** [comment] 2018-04-24 19:46
@lsiden Did you try `containerStyle={{ padding: 0 }}` ?

**Comment by xavier-villelegier** [comment] 2018-05-07 13:05
I think it's a duplicate of #1119

**Closed by xavier-villelegier** 2018-05-07 13:05 UTC
Labels: ⏳Awaiting Reply, 🔦 Help Wanted
