### ISSUE TITLE
Theme font color issue when using solid white buttons and clear/outline buttons

### ISSUE THREAD

**Issue by TheRealDerekLou** [react-native-training/react-native-elements#2030] opened 2019-08-20 05:55 UTC
**Explain what you did**
I'm trying to use the ThemeProvider to create solid white buttons with color text alongside outline buttons with white text (on a clear color background)

**Describe the bug**
I cannot simultaneously create both buttons in the way that I want to through the ThemeProvider

If I specify the font color to be the color, then it will render the solid white buttons with color text (good), but the outline buttons will render color text on a clear color background (bad).
![image](https://user-images.githubusercontent.com/29391289/63320997-5cb64e80-c2ed-11e9-8f6b-3a4bd1f4d57a.png)

Alternatively, if I try to specify the font color to be white, the the solid white buttons will have solid white text (bad), and the outline buttons will have white text on a clear color background (good).
![image](https://user-images.githubusercontent.com/29391289/63320960-401a1680-c2ed-11e9-8531-b497614fcd7f.png)

Getting around this seems like it would require component-level style which looks at the type of the button which would be tedious and eliminates a lot of the benefits of having button types. 

**Possible Solution**
It would be nice to have more flexibility in theming the font color of buttons dependent on their type. Currently, if a font color is specified in the theme, all buttons are given the same font color, even though generally a solid button would require a different font color than a clear/outline button.

Normally, this is avoided because of the default behavior of the font color assignment as shown on line 222 of [Button.js](https://github.com/react-native-training/react-native-elements/blob/next/src/buttons/Button.js) which gives differentiated colors dependent on type.
`color: type === 'solid' ? 'white' : theme.colors.primary`
However, this is only compatible with dark-colored buttons since it defaults to rendering white text on them, but it proves problematic when trying to make white buttons

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.1.0|
| react-native          |0.59.8|
| npm or yarn           |1.3.2|

**Comment by iRoachie** [comment] 2019-10-03 05:45
Duplicate of 1886

**Closed** 2019-10-03 05:51 UTC
Labels: :boom:  Bug
