### ISSUE TITLE
Cannot import Input component with v0.19.0

### ISSUE THREAD

**Issue by jadelmir** [react-native-training/react-native-elements#1025] opened 2018-03-20 09:43 UTC
### Descripwtion

1. i imported Input = import { Input } from "react-native-elements";
2. i used the component i exepected to work
3. actually an error occured 

i am using the lastest version of react-native elements

import { View, Text } from "react-native";
import React, { Component } from "react";
import Icon from "react-native-vector-icons/FontAwesome";
import { Input } from "react-native-elements";

const Inputs = props => (
	<View>
		<View>
			<Input placeholder="BASIC INPUT" />;
			<Text>HELLO HELLO</Text>
		</View>
	</View>
);

export default Inputs;

ERROR IS 
invariant violation :element type is invalid expected a string...

**Comment by xavier-villelegier** [comment] 2018-03-20 09:46
Hey @jadelmir, I think you checked the `v1.0.0-beta3` docs but are using the `v0.19.0` version of RNE.
You can use the last `beta` version by doing

```
yarn add react-native-elements@beta
```

**Comment by Grohden** [comment] 2018-03-20 17:23
had the same problem... i installed the 0.19.0, but the react native elements site default page is for the beta...

**Comment by xavier-villelegier** [comment] 2018-03-20 17:38
Yea that is to encourage people to use the beta 
cc @iRoachie, I guess it's too confusing to make the `v1.0.0-beta3` the landing page

**Comment by Grohden** [comment] 2018-03-20 17:46
@xavier-villelegier that worked XD, but the problem is that everyone just install with `npm i react-native-elements` without looking at the beta label in the site.. i would put an `npm install beta` right below the `try out `and `view components` button in the beta landing page

**Comment by iRoachie** [comment] 2018-03-20 17:49
There's an open issue for it right now, https://github.com/facebook/Docusaurus/issues/346

**Comment by xavier-villelegier** [comment] 2018-03-30 18:20
Closing this as it seems to be just an issue with the import name.

Be sure you look at the [good version of the docs](https://react-native-training.github.io/react-native-elements/versions.html) to know which components you can use

**Closed by xavier-villelegier** 2018-03-30 18:20 UTC
Labels: Awaiting Reply, Help Wanted
