### ISSUE TITLE
checkbox with image

### ISSUE THREAD

**Issue by fluvios** [react-native-training/react-native-elements#998] opened 2018-03-14 01:13 UTC
**DESCRIPTION**

is there possible to use checkbox with image in the right ?

**VERSION**

i using "react-native-elements": "^0.19.0"

thanks for the answer

**Comment by xavier-villelegier** [comment] 2018-03-14 08:35
Hey @fluvios ! This is planned for `v1.0.0-beta4` 🔥 💯 
Just closing this as a duplicate of #888

**Closed by xavier-villelegier** 2018-03-14 08:35 UTC
