### ISSUE TITLE
I'm having trouble adjusting the searchBar height

### ISSUE THREAD

**Issue by operate2v** [react-native-training/react-native-elements#885] opened 2018-02-07 08:56 UTC
<img width="361" alt="2018-02-07_17-49-44" src="https://user-images.githubusercontent.com/17904967/35906908-9b2f3418-0c2f-11e8-9a82-da2f70d80e00.png">

I need to reduce the height of searchBar.
However, you can not adjust the position of the icons and letters.
only android.
Do you have props for change?

platform         : android
RN-ver           : 0.52.0
rn-elements  : ^0.19.0
android-ver   : api24, 7.0

this is my code

```
<SearchBar
      placeholder="Search"
      platform={Platform.OS}
      inputStyle={{ height: Platform.OS === 'ios' ? 29 : 29 }}
      containerStyle={{
        height: 46,
        backgroundColor: 'white',
        borderTopWidth: 0,
      }}
    />
```

**Comment by iRoachie** [comment] 2018-02-07 23:08
This is really a duplicate of https://github.com/react-native-training/react-native-elements/issues/537. This will be fixed when the input component used for the searchbar is switched out for the new v1 input

**Closed by iRoachie** 2018-02-07 23:08 UTC
