### ISSUE TITLE
Error while updating property 'selectionColor' on 0.43.3 in Android

### ISSUE THREAD

**Issue by krailler** [react-native-training/react-native-elements#319] opened 2017-04-18 08:34 UTC
### Description

When updating to React 0.43.3, when I use the selectionColor property in any component that extends from TextInput on Android, it gives me the following error message. Did something change? In the documentation is still as before.

> Error while updating property 'selectionColor' of a view managed by: AndroidTextInput.

This has something to do? https://github.com/facebook/react-native/commit/ae57b25134c4db8be8539a0f0e6e52d46c850339

### Reproduction Steps and Sample Code

`import { FormInput } from 'react-native-elements'`
`...`
`<FormInput />`

### Additional Information

* React Native version: 0.43.3
* Platform: Android
* Development Operating System: MacOS

**Comment by tarang9211** [comment] 2017-04-19 16:44
Hey @krailler thanks for creating this issue. I just went through some of the issues in the react-native repo. Does this look like a possible solution? 

https://github.com/facebook/react-native/issues/5595#issuecomment-176434888

If not, we can take a deeper look into this.

**Comment by bozzmob** [comment] 2017-04-19 19:33
Hi @krailler, I analyzed a bit and think it trickles down to react-native. I go with your analysis, it has to be checked [react-native#13465](https://github.com/facebook/react-native/issues/13465).

**Comment by krailler** [comment] 2017-04-21 12:19
I fix it in https://github.com/facebook/react-native/issues/13465

**Comment by itsashis4u** [comment] 2017-05-22 19:28
I am building app with expo and I got this error when I tried using FormInput (normal TextInput works fine).

**Comment by Monte9** [comment] 2017-05-22 20:24
We are looking into this. Sorry about that. 

We will fix this asap and push a fix for it soon.
/cc @binoy14

**Comment by binoy14** [comment] 2017-05-23 12:44
Duplicate of #331 follow progress there

**Closed by binoy14** 2017-05-23 12:44 UTC
