### ISSUE TITLE
Component Button

### ISSUE THREAD

**Issue by StanislavVoronov** [react-native-training/react-native-elements#1313] opened 2018-07-18 15:51 UTC
**Explain what you did**
I want to set own color when I click on button, but underlayColor has not been handled via props, but interface has it. 

**Expected behaviour**
I can change the underlayColor of button component

**Describe the bug**
UnderlayColor has not been handled via props, but interface has it. 

**To Reproduce**
Set underlayColor of Button component

**Possible Solution**
Fix bug. Handle prop underlayColor of Button

**Your Environment (please complete the following information):**
VS Code

| software | version |
| -- | -- |
| 1.0.0-beta5 | |
| 0.56.0 | |
| npm| |

**Comment by iRoachie** [comment] 2018-07-18 15:53
Duplicate of https://github.com/react-native-training/react-native-elements/issues/1290

**Closed by iRoachie** 2018-07-18 15:53 UTC
