### ISSUE TITLE
Search Bar width tied to screen width

### ISSUE THREAD

**Issue by lsei** [react-native-training/react-native-elements#1145] opened 2018-04-26 15:11 UTC
1. I'm using the Search bar as a FlatList header. The FlatList is inside a wrapper which has padding on the left and right. 
2. Expecting the search bar to display properly inside the container. 
3. The search bar and cancel text is too far to the right and half out of view. 

Version: v1.0.0-beta4

Demo: https://snack.expo.io/ByQc5PypG

Having had a quick look at the source code I believe this is due to the reliance on device width which is used for width and the focus screen size. 

### Solution
At first glance I can see two possible solutions: 
A) Keep the current setup and expose an additional optional `containerWidth` prop which overrides `SCREEN_WIDTH` used in the component. The user is then responsible for determining the correct width themselves. 

B) Use `onLayout` on a container element to determine the available width and then use that for further layout calculations further down the line. 

Because container width is not available before at least one render has occurred there will need to be some workarounds to prevent awkward layouts before the width has been determined. 

Happy to work on a PR of either of those solutions seem viable.

**Comment by iRoachie** [comment] 2018-04-27 04:58
Duplicate of #861

**Closed by iRoachie** 2018-04-27 04:58 UTC
