### ISSUE TITLE
Can't animate Slider thumbStyle

### ISSUE THREAD

**Issue by mobiusnz** [react-native-training/react-native-elements#712] opened 2017-11-13 09:28 UTC
### Description

1. _Explain what you did:_ **Pass an animated style to `thumbStyle`**
2. _What you expected to happen:_ **The thumb button should animate**
3. _What actually happens:_ **The thumb button does not animate**

Also please include the version of `react-native-elements` that you are using.
`    "react-native-elements": "^0.18.2",
`
### Reproduction Steps and Sample Code

https://snack.expo.io/SkBSH1vkf

**Comment by xavier-villelegier** [comment] 2017-11-14 17:39
@mobiusnz Yep good catch 👍
The problem is that the transform you pass is overridden [here](https://github.com/react-native-training/react-native-elements/blob/master/src/slider/Slider.js#L404)
This should be fixed in the next release, but feel free to submit a PR!

**Comment by xavier-villelegier** [comment] 2018-01-28 22:29
@mobiusnz This was fixed in `v1.0.0-beta2`, now live on npm 🎉

**Closed by xavier-villelegier** 2018-01-28 22:29 UTC
Labels: Fixed - Next Release, bug
