### ISSUE TITLE
 Unrecognized font family 'material'

### ISSUE THREAD

**Issue by thanh90** [react-native-training/react-native-elements#1997] opened 2019-08-02 08:19 UTC
I upgraded my project to Expo 34, and got this error, only for iOS
![Screen Shot 2019-08-02 at 5 16 40 PM](https://user-images.githubusercontent.com/30317015/62355261-9c3d1680-b549-11e9-8fec-32607eb87cd7.png)
Anybody knows how to fix ? Thanks

**Comment by iRoachie** [comment] 2019-08-02 11:06
Duplicate of #1986

**Closed by iRoachie** 2019-08-02 11:06 UTC

**Comment by thanh90** [comment] 2019-08-02 13:12
i already installed react-native-vector-icons but still doesn't work

**Comment by thanh90** [comment] 2019-08-02 14:17
It seemed that I need to clear cache to make it run

**Comment by Slapbox** [comment] 2019-08-15 19:17
@iRoachie the solution from #1986 is incomplete. I can't overcome this error. Both are closed and my only option seems to be to be to roll back to Expo 33.

**Comment by Slapbox** [comment] 2019-08-15 19:34
By the way, I'm seeing this on Android. I'm pretty sure the issue comes from[ the Expo team's decision to rename all the relevant font families from hyphen separated to camelcase](https://expo.github.io/vector-icons/). I'm not sure what the logic there was, but using a type of `MaterialCommunityIcons` instead of `material-community`, and `MaterialIcons` instead of `material` works for me,
