### ISSUE TITLE
Button: Gray overlay when pressing without releasing a button  

### ISSUE THREAD

**Issue by msevestre** [react-native-training/react-native-elements#1547] opened 2018-11-02 00:52 UTC
**Explain what you did**
Using 1.0.0.beta6
I have a view with a Button.  The button style simply sets border radius to 30

**Expected behaviour**
When the button is pressed, the style of the button should not change. This is the behavior in iOS but does not quite work on Android. 

**Describe the bug**
On android, the button shows a gray square background that disappear as soon as the button is released. 

My button looks like so

```
<Button
  buttonStyle={styles.button}
  activeOpacity={0.8}
  onPress={this.handlePress}
 />
```
with
```
 button: {
  borderRadius: 30,
  height: 50,
  width: 200,
  backgroundColor: colors.primary,
  },
```
| software | version |
| -- | -- |
| react-native-elements |1.0.0.beta6 |
| react-native |0.55.4 |
| npm or yarn |yarn |

Cheers,
Michael

**Comment by iRoachie** [comment] 2018-11-02 00:55
This was fixed in https://github.com/react-native-training/react-native-elements/commit/56733235c9d5b5a919bbba7e8173c1e484d8e3cf. Will be available in 1.0.0

**Closed by iRoachie** 2018-11-02 00:55 UTC
Labels: :boom:  Bug

**Comment by msevestre** [comment] 2018-11-02 00:58
@iRoachie Ok cool. Sorry I tried to find the issue but did not managed to

And here is a screenshot as well 
![image](https://user-images.githubusercontent.com/1041237/47888072-d5105980-de18-11e8-9293-a4a6883bdcb8.png)
:)

**Comment by iRoachie** [comment] 2018-11-02 00:59
Yea it's fixed now, the problem was that we didn't apply the borderRadius to the container as well

**Comment by msevestre** [comment] 2018-11-02 01:10
@iRoachie I copied the button code locally to try it out. Behavior is the same
I also set the container border Radius to 30 in my case but that does not change how it looks. Same behavior. 

weird

**Comment by iRoachie** [comment] 2018-11-02 01:14
And this is on android right?

**Comment by msevestre** [comment] 2018-11-02 01:16
Yes android. Tried on phone and emulator. I am going to try fresh tomorrow and report my findings

**Comment by iRoachie** [comment] 2018-11-02 01:28
I don't think you pulled from the next branch. it works fine
https://www.useloom.com/share/d3beb78c69a84c1e82aeae82d2fbc74d

**Comment by msevestre** [comment] 2018-11-02 01:41
Ok cool. I'll try again tomorrow morning. Thanks again

**Comment by iRoachie** [comment] 2018-11-02 01:46
Sure np! Also when you use the next branch if you're working with expo you might see an error. Just comment out this line https://github.com/react-native-training/react-native-elements/blob/next/src/helpers/getIconType.js#L44 and the ones with antdesign

**Comment by msevestre** [comment] 2018-11-05 18:32
@iRoachie Ok I tried on a brand new project and it works as expected
However just changing the content of Button.js does not do the trick so probably some other code has changed. Once the release is out, I'll give another try. Thanks again

**Comment by alainib** [comment] 2018-12-04 13:13
any change for this bug ? i'm tryed on version beta5 and beta7 and cannot solve it 


    <Button containerViewStyle={{ borderRadius: 25 }} buttonStyle={{ width: 145, height: 45, borderRadius: 25 }} title={"text"} />

or 
 
  <Button buttonStyle={{ width: 145, height: 45, borderRadius: 25 }} title={"text"} />


Is there a way to completly hide the grey on press overlay (of touchableOpacity) like on IOS ?

**Comment by iRoachie** [comment] 2018-12-05 08:36
I am not sure what you are referring to, do you mean the button dimming when pressed?

**Comment by alainib** [comment] 2018-12-05 09:01
> 
> 
> I am not sure what you are referring to, do you mean the button dimming when pressed?

with your code, when i press the button all the background become black 

![image](https://user-images.githubusercontent.com/7910081/49502075-a00e8100-f874-11e8-8e60-9083a6edd133.png)

**Comment by iRoachie** [comment] 2018-12-05 13:34
@alainib if you can reproduce this on https://snack.expo.io i'd appreciate it. But we don't have anything on our lib that'll give you a black background like that by default
