### ISSUE TITLE
<Tile> prop "activeOpacity " doesn't work

### ISSUE THREAD

**Issue by keith527** [react-native-training/react-native-elements#479] opened 2017-07-11 06:24 UTC
### Description
I use the <Tile> in my Demo, But I want to set activeOpacity to "0.95",but doesn't work.

There is my code:

``` 
<Tile imageSrc={require('../image/sea.jpg')}
                 activeOpacity={0.95}
                 onPress={() => alert('onPress')}
            />
```

I use the latest version of react-native-elements

**Comment by Monte9** [comment] 2017-07-11 06:40
Unable to reproduce it. Please see this [Snack demo](https://snack.expo.io/BJ0nMeGBZ)

**Comment by mateen-hussain** [comment] 2018-01-24 13:17
@Monte9 I have the same problem too. I'm trying to disable the touch feedback on a tile.

```
<Tile
			imageSrc={defaultImagePath}
			title={registration}
			containerStyle={styles.TileContainer}
			titleStyle={styles.TileTitle}
			imageContainerStyle={styles.TileIconStyle}
			activeOpacity={1}
		/>
```

I tried various values between 0-1 to disable the touchfeedback but I dont see any effect.

```
    "react": "16.0.0",
    "react-native": "0.50.0",
    "react-native-elements": "0.17.0",
```

**Comment by xavier-villelegier** [comment] 2018-01-24 14:32
@mateen-hussain Yes you're right.
You can see that the `activeOpacity` is taken [here](https://github.com/react-native-training/react-native-elements/blob/master/src/tile/Tile.js#L27) but not passed to the `TouchableOpacity`, because not in `...atributes` anymore.

Feel free to open a PR to fix it, it is as simple as adding `activeOpacity={activeOpacity}` to the `TouchableOpacity` 👌

**Comment by mateen-hussain** [comment] 2018-01-24 15:34
Would love to contribute. let me give it a try.

**Comment by xavier-villelegier** [comment] 2018-01-24 15:41
@mateen-hussain, @lex111 has already opened a PR, have a look at #839.
There is a bunch of "good first issue"s you can try to take down ! Give [them](https://github.com/react-native-training/react-native-elements/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) a shot 💪

**Comment by xavier-villelegier** [comment] 2018-01-28 22:27
Hey guys, fixed in `v1.0.0-beta2`, just released 👍

**Closed by xavier-villelegier** 2018-01-28 22:27 UTC
Labels: Fixed - Next Release, bug
