### ISSUE TITLE
More Customization on SearchBar

### ISSUE THREAD

**Issue by Bonobomagno** [react-native-training/react-native-elements#1128] opened 2018-04-19 11:22 UTC
### Description
`react-native-elements   version "1.0.0-beta4"`

i want to change inner background of the theme
### Reproduction Steps and Sample Code

```
lightTheme
platform={'ios'}

```
i'm trying to change the input area, but if i use only `inputStyle `prop, i can't change the background of the left icon, or the small area on the right.

### Solution

with **react-devtools** i found that setting `backgroundColor `of the `AnimatedComponent`, is what i want. So, i think that using `inputStyle` for the AnimatedComponent style (or same tree level node) is the right thing to do.
Or just add an `inputAreaStyle `(?) or something like that.

**Comment by iRoachie** [comment] 2018-04-19 13:11
Hey @Bonobomagno, you'll want to make use of the `inputContainerStyle` and `containerStyle` prop. Here's an example of the two of them in action https://snack.expo.io/H1F8BMU2M

**Comment by Bonobomagno** [comment] 2018-04-19 13:52
yes, but there is no documentation for that!
https://react-native-training.github.io/react-native-elements/docs/searchbar.html

**Comment by kyler-hyuna** [comment] 2018-04-19 13:56
Thanks for bringing that up! Will add it to the next relaase

**Comment by iRoachie** [comment] 2018-04-19 13:56
Thanks for bringing that up! Will add it to the next release

**Comment by iRoachie** [comment] 2018-04-19 13:57
We have an issue for it already https://github.com/react-native-training/react-native-elements/issues/1123

**Comment by xavier-villelegier** [comment] 2018-04-19 20:19
Closing this as duplicate of #1123

**Closed by xavier-villelegier** 2018-04-19 20:19 UTC
Labels: ⏳Awaiting Reply, 🔦 Help Wanted
