### ISSUE TITLE
Raised button in 1.0.0

### ISSUE THREAD

**Issue by James2516** [react-native-training/react-native-elements#1110] opened 2018-04-13 13:10 UTC
I noticed that [raised](https://react-native-training.github.io/react-native-elements/docs/0.19.0/button.html#raised) prop is removed in 1.0.0.

How do we go about creating a raised button now?

**Comment by iRoachie** [comment] 2018-04-13 13:13
Duplicate of #1028

**Closed by iRoachie** 2018-04-13 13:13 UTC
