### ISSUE TITLE
Production builds for web won't render because required propType imgSource in Tiles is undefined.

### ISSUE THREAD

**Issue by jacklinton** [react-native-training/react-native-elements#960] opened 2018-03-03 07:08 UTC
Production builds for web won't render because required prop imgSource in Tiles is undefined. Dev builds have no problems. I've temporarily solved the issue by going into the library and deleting the 'isRequired' part of the definition, but I'm looking for help with a more long-term solution that preferably doesn't involve my using a custom version of the package.

1. I created a react-native-web app starting with create-react-app and I have not ejected.
2. I expected required props in modules that I'm not using in my app to be irrelevant.
3. Compiled production build fails to render because required prop in tiles module is undefined.

```
{
  "name": "xxx",
  "version": "xxxxx",
  "private": true,
  "dependencies": {
    "aws-amplify": "^0.2.6",
    "aws-amplify-react": "^0.1.32",
    "aws-amplify-react-native": "^0.2.3",
    "babel-plugin-transform-imports": "^1.4.1",
    "expo": "^25.0.0",
    "glob": "*",
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-dom": "^16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-calendars": "^1.17.1",
    "react-native-elements": "^0.19.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gesture-handler": "^1.0.0-alpha.41",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-tab-view": "^0.0.74",
    "react-native-web": "^0.5.1",
    "react-native-webview-quilljs": "^0.1.45",
    "react-navigation": "^1.2.1",
    "react-scripts": "1.1.1",
    "rn-prompt": "^1.0.2"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "./node_modules/.bin/webpack-dev-server -d --config ./webpack.config.js  --inline --hot --colors --content-base public/",
    "build": "NODE_ENV=production ./node_modules/.bin/webpack -p --config ./webpack.config.js",
    "test": "react-scripts test --env=jsdom",
    "eject-web": "react-scripts eject",
    "start-native": "react-native-scripts start",
    "eject-native": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test-native": "node node_modules/jest/bin/jest.js --watch",
    "test-both": "npm run test-web && npm run test-native",
    "cleanup": "rm -rf $TMPDIR/haste-map-react-native-packager-*  && rm -rf $TMPDIR/react-* && yarn cache clean && yarn"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "devDependencies": {
    "babel-plugin-react-native-web": "^0.5.1",
    "babel-preset-expo": "^4.0.0",
    "flow-bin": "^0.65.0",
    "react-native-scripts": "^1.11.1",
    "react-test-renderer": "^16.2.0"
  }
}
```

I realize this isn't exactly the intended use of the package, but I would appreciate some advice and insight on why I'm having this problem and perhaps a solution. Is it simply a configuration issue? Webpack related?

### Solution

I am aware that there is a webpack plugin that will strip propTypes from components on production builds. Is that a good 'best practice'? From necolas at RNW, "Note, some components use propTypes in render and this will need to be accounted for." I don't think that applies here, but I don't want to break some functionality inadvertently. This seems heavy handed.

I guess what I really want is a go-ahead to strip the propTypes from the package during production builds from someone more knowledgeable than I am. If prop-types is only relevant outside production, shouldn't be installed as a dev dependency?

**Comment by jacklinton** [comment] 2018-03-03 16:37
I'm going to add some notes in this post. Perhaps this discussion belongs in react-native-web territory, however since it directly involves this package I will keep it here for now.

The problem defined: 

When compiling/bundling for web, React Native packages must be included in the babel loader in order to be properly transpiled for web. That means the proptypes end up in the production build where they normally wouldn't belong if it was just normal source code for the project. Any proptype in the dependency package that has an 'isRequired' label won't have a default value and will therefor evaluate to undefined during build which breaks the application.

There is a babel plugin to remove proptypes during transpilation which, if I understand correctly, will strip the proptypes from anything that goes through the babel loader, which means all of the react native packages you've included in the configuration.

However, some packages require the use of proptypes to function properly ex. React-Native-Vector-Icons and so it will break or perform unpredictably in the production build.

Solution?

As it stands in my mind right now... there is no equitable solution. Both the transpilation process and the proptypes are required in order to operate correctly after build. They are mutually exclusive.

A possible patch is to configure the proptype stripping plugin so that it only transpiles the packages causing problems. I'm not sure if that is possible, but it's worth a try.

Another idea is to simply strip the 'isRequired' portion from the offending proptypes, again during the build. Accompanied by... maybe some kind of warning to the user/developer that they must provide that proptype? How would such a warning be applied? In the application UI?

Can required proptypes simply be ignored and hope all goes well with how the package is used?

Include a default for the required proptype?

Ask package developers to provide a version of the package without required proptypes if they want to use it for web?


Obviously, my conclusion is that there is no equitable solution except maybe to create a custom version of the package for web use.

I know ya'll are working on web compatibility in the new beta, and maybe that will solve the problem once and for all once it's ready... for this package anyway. Otherwise, the developer using the package for web will simply have to provide their own solution. This should be react-native-web's problem I think. From previous experience in reading though issues over there, I don't think the creator will be equitable to such a solution - the package simply wasn't developed for this use case. The burden then lies on the community to create a solution for itself. Fork RNW, or the packages causing problems, fix them, and then offer them up to NPM.

I would love to hear your opinions! Even though I think this issue can be closed. The original question/problem/solution has been worked through to my satisfaction.

**Comment by jacklinton** [comment] 2018-03-03 18:10
I think my brilliant solution for now is just to add an additional process to the build script that does a find/replace on the bundle to remove all '.isRequired' from the document. Maybe I'll have it create a log file of where they are all located in case it causes any issues. At least other people will be able to clone and build the repo and get a working production build without having to go in and modify node_modules.

**Comment by Monte9** [comment] 2018-03-07 09:33
Firstly, thanks for documenting & sharing your learnings as you try to setup CRN + RNE. I am sure these learnings would be useful for someone trying to do that same.

> Maybe I'll have it create a log file of where they are all located in case it causes any issues.

I think that would be really useful for use @jacklinton! That way we can see the number of changes needed and come up with a plan to address those.

**Comment by geminiyellow** [comment] 2018-03-16 04:51
got the same error when use react-native-web in `production` mode.

```
Uncaught TypeError: Cannot read property 'isRequired' of undefined
    at Object.<anonymous> (bundle.js:formatted:47945)
    at D (bundle.js:formatted:450)
    at n (bundle.js:formatted:25)
    at Object.<anonymous> (bundle.js:formatted:47982)
    at D (bundle.js:formatted:450)
    at n (bundle.js:formatted:25)
    at Object.<anonymous> (bundle.js:formatted:62827)
    at D (bundle.js:formatted:450)
    at n (bundle.js:formatted:25)
    at Object.<anonymous> (bundle.js:formatted:62895)
```

and track the error, got this

`/node_modules/react-native-elements/src/tile/FeaturedTile.js"`

![image](https://user-images.githubusercontent.com/929878/37504356-1f039fdc-2921-11e8-8e7c-b89ba93dd82f.png)

**Comment by Monte9** [comment] 2018-03-17 16:19
If this is the only blocker for using RNW in production mode, we can easily get rid of the `isRequired` and just add a null check on the component itself. Should be a quick fix. Let me know if that would fix your issue for now.

**Comment by jacklinton** [comment] 2018-03-18 08:43
As far as I can tell, that is the case. I would very much appreciate the fix!

**Comment by geminiyellow** [comment] 2018-03-19 01:51
yep

**Comment by giacomocerquone** [comment] 2018-04-01 03:05
woo jeesus, happened to be here for a completely another reason and now I'm getting why react styleguidist is not working when the docs are compiled... I can confirm this bug affetcs also 0.19.0 sadly

**Comment by giacomocerquone** [comment] 2018-04-02 22:46
So let's see @jacklinton 

As far as I can tell, Dan Abramov removed proptypes in production too in his CRA https://github.com/facebook/create-react-app/issues/209

And it seems to me the right thing to do. But as I understood from this issue, this cannot be done because of packages like react-native-vector-icons, but again... I'd say "their problems". What do I mean with this?

I mean that it's ok to just remove the "isRequired" for now, but in the mean time we should consider the deletion of proptypes in production advising the same thing for all the other packages maintainers like vector icons

**Also if we don't need runtime type checking on props, we could switch to flow**

**Comment by jacklinton** [comment] 2018-04-03 01:02
If I catch your meaning, you're saying it should be considered 'best practice' for package creators/maintainers not to rely on proptypes in production code for type checking or for the _actual functionality of the package_... or at all for anything in production. (I think the Bootstrap package is guilty of the same thing, and who knows how many others).

In that case I completely agree. At the very least it would reduce the size of the bundled package in production builds and it would alleviate unforeseen problems like this one. I'm not sure why package producers started using this practice to begin with. I guess it was supposed to be a clever trick or shortcut where the package would have different behaviors depending on the type of the parameters passed to the components that rely on proptypes. It's puzzling why removing proptypes in production became a default [best] practice for developers in one situation but not in another. It's easy for us to look back at it now and say, "that wasn't as smart as it appeared to be."

The question is, how do we get the word out? How do we approach the creators of standard packages like Bootstrap or RN Vector Icons and make the case that they are using a bad practice in their code? I guess the natural answer is to figure out a better way and submit a PR. But that only works for the ones we know about. Proptypes in production could be a widely used practice for package creators. From what I hear, removing them as a user of the package during the production build process may not lead to an exception being thrown or any other obvious indicator other than perhaps some unpredictable behavior of certain components at runtime. In other words, it's clearly not an acceptable solution to the problem. That's not the type of thing that could easily be rooted out in a systematic way without actually going through the source code of all the dependencies that you use.

Also, what's to stop the developers of the package from claiming that what we are trying to do (react native for web) is not the intended use of the package, so why should they change it? The problem is political as well as functional. We would need to convince these folks that using proptypes in their production code is a bad practice and that they need to find a better way and rewrite the code. It may turn out to be a tough sell.

**Comment by xavier-villelegier** [comment] 2018-04-03 08:03
@giacomocerquone Is #1062 ready to merge ? Did you test that it works with production builds for web ?
@jacklinton This will be released as `v0.19.1` because it seems a bit critical

**Comment by giacomocerquone** [comment] 2018-04-03 09:58
@xavier-villelegier it works for me, tried to compile my docs again on react-styleguidist (that compiles this stuff with rnw) with this changes.
I believe you can merge it

**Comment by xavier-villelegier** [comment] 2018-04-03 10:04
@jacklinton @geminiyellow @giacomocerquone #1062 has been merged into the `stable` branch. This will be released as `v0.19.1` asap, but in the meantime you can directly use the `stable` branch.

```
yarn add "https://github.com/react-native-training/react-native-elements.git#stable"
```

I'll let this issue open to make sure that we'll remove `isRequired` for the next `v1.0.0-beta5` release too (in `Tile`, `FeaturedTile`, `Overlay`)

**Comment by giacomocerquone** [comment] 2018-04-03 10:11
@jacklinton Yes, it's exactly what I meant!
Anyway for the 1.0.0-beta5 I'd say to fix this in other ways, this fix just seemed like a hack.

@xavier-villelegier Are there already some plans to use flow in the future instead of proptypes?

**Comment by iRoachie** [comment] 2018-04-03 14:53
@giacomocerquone Maybe we can open a new issue to talk about static typing. I've made suggestions for it before but that was a while ago

**Comment by jacklinton** [comment] 2018-04-05 02:35
Amazing, thanks for your help and responsiveness everyone!

**Comment by xavier-villelegier** [comment] 2018-04-07 09:52
@jacklinton @giacomocerquone @geminiyellow 
Closing this as the version `v0.19.1` is out on npm, you can have a look at the [release notes](https://github.com/react-native-training/react-native-elements/releases/tag/v0.19.1). Feel free to open a new issue if there is an other critical bug as this one 👍

**Closed by xavier-villelegier** 2018-04-07 09:52 UTC
Labels: ✅ Fixed - Next Release, ❔Question, 🤔Thoughts?
