### ISSUE TITLE
[SearchBar] onClear with "default" platform

### ISSUE THREAD

**Issue by LouisJS** [react-native-training/react-native-elements#1184] opened 2018-05-09 10:32 UTC
### Description

I've implemented a Searchbar and tried the onClear feature.
It doesn't work when you let the "default" platform.

I tried it on simulator and real device.
Here is a snack that shows the issue

### Reproduction Steps and Sample Code

https://snack.expo.io/rkKtTBx0G

using `react-native-elements beta5`

**Comment by xavier-villelegier** [comment] 2018-05-09 10:39
@LouisJS Good catch ! 👏  We refactored the SearchBars in beta5 because they were inconsistent, but the default one doesn't trigger the `clear` event.

The issue is here:
https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/searchbar/SearchBar-default.js#L18-L23

We need to move the `defaultClearIcon` in the component and add `onPress: this.clear`, as it is for the iOS SearchBar for example:
https://github.com/react-native-training/react-native-elements/blob/d4da856a7f105c814cc162e507b48c49399cabef/src/searchbar/SearchBar-ios.js#L91-L97

**Comment by LouisJS** [comment] 2018-05-09 12:10
@xavier-villelegier PR is open 👍

**Comment by xavier-villelegier** [comment] 2018-05-09 12:32
Merged ! Will be live in beta6

**Comment by xavier-villelegier** [comment] 2018-05-09 12:56
@LouisJS I'll just let this opened until beta6 is actually released 👍 People can see if the issue they want to submit is already fixed by checking the `Fixed - Next Release` opened issues

**Comment by tux-tn** [comment] 2018-10-04 14:15
@xavier-villelegier any roadmap/schedule for beta6?

**Comment by iRoachie** [comment] 2018-10-09 17:22
@tux-tn Releases today!

**Closed by iRoachie** 2018-10-09 17:22 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release, 👶 Good First Issue

**Comment by iRoachie** [comment] 2018-10-10 21:59
Live now in [1.0.0-beta6](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta6)!
