### ISSUE TITLE
 SocialIcon OnPress does not work when Debug JS Remotely is enabled

### ISSUE THREAD

**Issue by YulianD** [react-native-training/react-native-elements#649] opened 2017-10-11 17:50 UTC
### Description

Hi everyone, I have the following problem with **SocialIcon**: When I enable **Debug JS Remotely**, the OnPress option stops working and throws the following message: 

> please attach method to this component
![please attach](https://user-images.githubusercontent.com/11492518/31457210-b3d5ddc0-ae81-11e7-8094-42747db383f0.PNG)

I've run the app on several phones and it all happens the same.

these are my dependencies

    "expo": "^21.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.4",
    "react-native-elements": "^0.17.0"

And this is my code

    import React from 'react';
    import { StyleSheet, Text, View } from 'react-native';
    import {SocialIcon} from 'react-native-elements';

    export default class App extends React.Component {
    
      loginWithFacebook = () => {
        alert('It Works');
    }

      render() {
        return (
          <View style={styles.container}>
            <Text>Open up App.js to start working on your app!</Text>
            <Text>Changes you make will automatically reload.</Text>
            <Text>Shake your phone to open the developer menu.</Text>
    
            <SocialIcon title="login_facebook" 
                button raised type="facebook" 
                style={{ width: 300, height: 40 }} 
                onPress={this.loginWithFacebook} />
          </View>
        );
      }
    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      },
    });`

**I appreciate your help**

**Comment by btav** [comment] 2017-10-12 00:10
Hi @YulianD,

I quickly reviewed the code and it seems like if you don't pass in a `onLongPress` value, you will see that console log message. Try passing the same function as `onPress` into `onLongPress`.

**Comment by iRoachie** [comment] 2017-10-12 19:59
Hey, I created a replica project with your code, and I'm unable to reproduce the error. You can see a video I did here with the exact setup.

https://www.useloom.com/share/7535b7955e514b398b13e503b6a0bf09

**Comment by YulianD** [comment] 2017-10-12 22:31
@iRoachie hello, I forgot to mention that the problem persists in Android. and @btav is obligatory pass a value in onPress, because when i use Button from 'react-native', the problem is not present

**Comment by iRoachie** [comment] 2017-10-24 00:48
@YulianD I did the same example on android as you can see here https://www.useloom.com/share/8e53deb34c3443d58b05e727105889cd. Still no errors or warnings.

**Comment by cipriancaba** [comment] 2017-10-24 13:21
I'm experiencing the same problem with any `onPress` handler.. If I stop the debugger the buttons start working..

**Comment by fabriciovergal** [comment] 2017-11-23 12:39
The onLongPress is being triggered instead of onPress.
For a quick fix just add the same method in the onLongPress prop.

https://github.com/facebook/react-native/issues/4944

**Comment by iRoachie** [comment] 2017-12-04 00:59
Closing this issue, not sure how we can work on resolving this problem as we can't replicate it on a new project.

**Closed by iRoachie** 2017-12-04 00:59 UTC
Labels: awaiting-reply, Help Wanted

**Comment by gorvinsky** [comment] 2018-02-06 09:56
Still having this issue and only happen when connected to Chrome debugger.

**Comment by borgogelli** [comment] 2018-10-20 22:35
+1

**Comment by LondonJammo** [comment] 2019-02-09 12:32
Yes, this occurs with the chrome debugger active (remote debugging),

**BUG
