### ISSUE TITLE
Material Icons is not a system font error when using List and ListItem

### ISSUE THREAD

**Issue by nausharipov** [react-native-training/react-native-elements#1559] opened 2018-11-06 04:36 UTC
The problem:
`fontFamily 'Material Icons' is not a system font and has not been loaded through Font.loadAsync.`

I tried to solve the problem with this method https://javascriptrambling.blogspot.com/2018/03/expo-icon-fonts-with-react-native-and.html. I added Material Icons into AppFontLoader, but it didn't help:

```
import React from "react";
import { AppLoading, Font } from "expo";
import MaterialIcons from "../node_modules/@expo/vector-icons/fonts/MaterialIcons.ttf";
import FontAwesome from '../node_modules/@expo/vector-icons/fonts/FontAwesome.ttf';
import RobotoMedium from '../node_modules/@expo/vector-icons/fonts/Roboto-Medium.ttf';
import RobotoRegular from '../node_modules/@expo/vector-icons/fonts/Roboto-Regular.ttf';
import Roboto from '../node_modules/@expo/vector-icons/fonts/Roboto.ttf';

class AppFontLoader extends React.Component {
  state = {
    fontLoaded: false
  };

  async componentWillMount() {
    try {
      await Font.loadAsync({
        FontAwesome,
        MaterialIcons,
        RobotoMedium,
        RobotoRegular,
        Roboto
      });

      this.setState({ fontLoaded: true });
    } catch (error) {
      console.log("error loading icon fonts", error);
    }
  }

  render() {
    if (!this.state.fontLoaded) {
      return <AppLoading />;
    }

    return this.props.children;
  }
}

export { AppFontLoader };
```

I also tried adding space to the file "Material Icons.ttf", but it didn't help either. 
How to solve the problem?

**Comment by iRoachie** [comment] 2018-11-06 05:54
Duplicate of #1005

**Closed by iRoachie** 2018-11-06 05:54 UTC
