### ISSUE TITLE
SearchBar Android clear icon does not appear onMount 

### ISSUE THREAD

**Issue by SkyRune** [react-native-training/react-native-elements#1594] opened 2018-11-21 22:42 UTC
### Description of the bug

If the androids searchbar is mount and already has text in the input the clear icon does not appear.

In my case I have an android search bar and a scroll view, when I scroll down I make the searchbar unmount, and when I scroll top it's render with the content it has.

### Why it occurs ?

The clear icon is display according to `this.state.isEmpty` value.

`this.state.isEmpty` is only update when the text change. It should also be update once, when the searchbar is mounted for the first time.

### Solution 

One solution is to update the state of the component SearchBar in the componentWillMount() like this : 

```
componentWillMount() {
    this.setState({ isEmpty: this.props.value === "" });
  }
```

**Comment by iRoachie** [comment] 2018-11-22 02:19
Duplicate of #1247

**Closed by iRoachie** 2018-11-22 02:19 UTC
