### ISSUE TITLE
borderLeftColor doesn't work on Android

### ISSUE THREAD

**Issue by olcayertas** [react-native-training/react-native-elements#1922] opened 2019-06-20 11:36 UTC
I am trying to show red left border with 23 width for new list items using `borderLeftWidth` and `borderLeftColor` with below code:

```
import React from "react";
import { ListItem as ListElement} from "react-native-elements";

export const ListItem = ({ borderLeftWidth, borderLeftColor, backgroundColor, ...props }) => {
  const titleStyle = {
    fontSize: 13,
    lineHeight: 16,
    color: "#2e2e2e",
    fontWeight: "bold"
  };
  const subtitleStyle = {
    fontSize: 12,
    lineHeight: 16,
    color: "#2e2e2e"
  };
  const containerStyle = {
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 5,
    borderColor: "#d6d6d6",
    borderLeftWidth: borderLeftWidth === undefined ? 23 : borderLeftWidth,
    borderLeftColor: borderLeftColor || "#d6d6d6",
    backgroundColor: backgroundColor || "#ffffff",
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10
  };
  return (
    <ListElement
      rightTitleStyle={{ fontSize: 12 }}
      titleStyle={titleStyle}
      subtitleStyle={subtitleStyle}
      containerStyle={containerStyle}
      {...props}/>
  );
};
```
```
const rightTitle = formatDate(item.created_at);
const borderLeftColor = item.is_read ? null : primaryColor;
return (
  <TouchableOpacity onPress={() => this.readCorrespondence(item)}>
    <ListItem
      title={item.reference_code}
      rightTitle={rightTitle}
      rightTitleStyle={{ fontSize: 12 }}
      subtitle={item.subject}
      borderLeftColor={borderLeftColor}
    />
  </TouchableOpacity>
);
```
**Expected behaviour**
This is working on iOS:

<img width="335" alt="ios" src="https://user-images.githubusercontent.com/1506019/59845392-f7ce8e80-9365-11e9-9ec0-99416b3ae38e.png">

**Describe the bug**
On Android `borderLeftColor` doesn't work:

<img width="297" alt="android" src="https://user-images.githubusercontent.com/1506019/59845469-2b111d80-9366-11e9-9f9e-110f98262391.png">

**To Reproduce**
You can reproduce the problem on [snack.expo.io/S1tzylKJB](https://snack.expo.io/S1tzylKJB). 

**Environment **

| software              | version |
| --------------------- | ------- |
| react-native-elements | 1.1.0 |
| react-native          |    0.59.9     |
| npm or yarn           |    6.9.0     |

**Comment by olcayertas** [comment] 2019-06-20 11:55
I think it is related to this: https://github.com/facebook/react-native/issues/19981

**Comment by iRoachie** [comment] 2019-07-15 00:23
Yep just confirmed https://snack.expo.io/@roach_iam/moody-raisins. Closing since this an upstream issue.

**Closed by iRoachie** 2019-07-15 00:23 UTC
