### ISSUE TITLE
Button color displaying 2 background color and rating doesnt display the star

### ISSUE THREAD

**Issue by cafeasia3** [react-native-training/react-native-elements#1561] opened 2018-11-07 02:05 UTC
react-native-elements 1.0.0beta7
RN 0.57
tested on android device and emulator

The button display in 2 blue color like on this picture
![0225761e-b217-4d5f-91f1-2419933291a4](https://user-images.githubusercontent.com/32291274/48105783-67768a00-e26b-11e8-995f-89c395aa1709.jpg)

and for the rating, it only display yellow block like this picture
![1d059217-fb38-456b-9937-5403b9ba6b02](https://user-images.githubusercontent.com/32291274/48105801-7f4e0e00-e26b-11e8-87c9-9bf5b3e54422.jpg)

I have installed react-native-vectors too and the fonts on android/app/src/main/assets/font

This is my button code
```
<Button
          title='Next'
          titleStyle={{ fontSize: 20 }}
          onPress={()=> this.props.actions.search}
          iconRight
          icon={
            <Icon
              name='arrow-right'
              size={20}
              color='white'
            />
```

and the rating

```
<Rating
          fractions={1}
          readonly
          startingValue={parseFloat(item.star)}
          imageSize={20}
          style={{ alignSelf:'flex-start' }}
        />
```
Any idea What cause the problems?

**Comment by iRoachie** [comment] 2018-11-07 02:07
Alright two issues here.

The button issue is fixed and will be in  v1.0.0(next release). The issue was that we were adding the elevation on the wrong View.

The Rating one i have to look into, haven't encountered that before

**Comment by iRoachie** [comment] 2018-11-07 02:09
I couldn't reproduce the rating error. This is how it renders for me https://snack.expo.io/@roach_iam/arrogant-truffle

**Comment by cafeasia3** [comment] 2018-11-20 10:49
The rating is fine now, I just need to rebuild, any workaround for the button?

**Comment by iRoachie** [comment] 2018-11-20 12:04
There's no workarounds right now I can think of, will just have to wait for the new version to release.

**Closed by iRoachie** 2018-11-20 12:04 UTC
Labels: 🔦 Help Wanted
