### ISSUE TITLE
Buttons from the parent component appearing on top of the Overlay [beta4]

### ISSUE THREAD

**Issue by razvanilin** [react-native-training/react-native-elements#1130] opened 2018-04-22 19:22 UTC
### Description

Hi there, I just updated to beta4 from beta3 and modified the code accordingly. I'm now experiencing an issue with the Overlay component. All the buttons from the parent component appear on top of the overlay. They are not clickable, but they can be seen as below:

**The four button on the top should be behind the Overlay**

![screenshot_20180422-194644](https://user-images.githubusercontent.com/5342321/39098989-a6e1bc34-466a-11e8-83fa-2f81a06213cb.png)

1. Explain what you did

Updated from beta3 to beta4
Placed Overlay at the end of render method

2. What you expected to happen

Like in beta3, my Overlay was supposed to render on top of everything

3. What actually happens

The buttons from the render method appear on top of my Overlay element unless I wrap everything other than the overlay into a ScrollView

Also please include the version of `react-native-elements` that you are using.

v1 Beta4

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.

```
      <View style={{ flex: 1 }}>
            <Button
              icon={
                <Icon
                  name="md-checkmark-circle"
                  type="ionicon"
                  size={24}
                  color="white"
                />
              }
              buttonStyle={[styles.button, styles.divider]}
              textStyle={{ fontFamily: "SourceSansPro-Bold", fontWeight: "400" }}
              title="Save"
              onPress={this._updateUser}
              loading={this.state.loading}
            />

            
          <Overlay
            isVisible={this.state.loginVisible}
          />
      </View>
```

### Solution

No fix so far other than wrapping the other content into a ScrollView

**Comment by iRoachie** [comment] 2018-04-22 19:36
Closing as duplicate of https://github.com/react-native-training/react-native-elements/issues/1112

**Closed by iRoachie** 2018-04-22 19:36 UTC
