### ISSUE TITLE
Cache Button Fonts

### ISSUE THREAD

**Issue by gamingumar** [react-native-training/react-native-elements#490] opened 2017-07-14 12:32 UTC
How to cache fonts before starting the expo app. 
I am using button in my welcome screen like this
`<Button
            large
            raised
            icon={{ name: 'location-on' }}
            title="Use My Current Location"
            backgroundColor={APP_GREEN_COLOR}
            color="white"
            onPress={() => {
              this.props.navigation.navigate('SignIn');
            }}
          />`
if the user is already signed in i check that in componentDidMount using redux state, i navigate the user to home screen. but i get the error because of this icon

> `Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
Please check the code for the Icon component.`

**Comment by binoy14** [comment] 2017-07-18 02:37
@gamingumar I was not able to recreate it, I don't think this is caused because of the button. As a test, can you try removing the button and see if it still an issue. If it is we can look at it.

**Comment by gamingumar** [comment] 2017-07-20 10:58
@binoy14 i have checked, the issue is being caused because of icon font, if i comment it out the issue is solved, also in ios it takes a lot of time to load fonts, i want to cache fonts

**Comment by iRoachie** [comment] 2017-07-20 12:29
That seems pretty odd, I’ve never encountered with react-native-vector-icons on iOS and I have a few apps in production. I’m interested to see if this a problem with how expo loads fonts asynchronously.

**Comment by keyeh** [comment] 2017-07-24 07:54
I'm also using Exponent and getting the same error with the same behavior; It only happens with the `icon` prop.
```jsx
        <Button
          icon={{ name: "envira", type: "font-awesome" }}  // will cause warning
          title={"Next"}
          onPress={this._handleNextButtonPress}
          style={styles.nextButton}
        />
```

I'm on "expo": "19.0.0", "react": "16.0.0-alpha.12"

**Comment by xavier-villelegier** [comment] 2017-07-26 19:56
Hey @gamingumar 
In the Tab Navigation demo of expo, they cache fonts like that:

```js

import { Font, AppLoading } from 'expo';
import { FontAwesome } from '@expo/vector-icons';

async componentWillMount() {
  await Font.loadAsync(FontAwesome.font);
  this.setState({ fontsAreLoaded: true });
}

render() {
  const { fonstAreLoaded } = this.state;
  return !fontsAreLoaded ? <AppLoading/> : …
}
```

if you use icons from multiple fonts, you load them like that:
```js
await Font.loadAsync({
  fontawesome: FontAwesome.font,
  ionicon: Ionicon.font,
  …
});
```

With that, the font is cached during the loading screen, and you don't have to wait for the icon to appear. Maybe it will do the job for your issue.

**Comment by Monte9** [comment] 2017-07-27 18:34
@xavier-villelegier thanks for the detailed example. 👏 

I think that's the right way to do it.. we are doing something similar in the `/example` app on `v1` branch. Check it out [here](https://github.com/react-native-training/react-native-elements/blob/v1/example/src/views/login/screen1.js#L29).

**Comment by gamingumar** [comment] 2017-07-31 13:10
Font.loadAsync throws error `
Possible Unhandled Promise Rejection (id: 0):
TypeError: asset.downloadAsync is not a function. (In 'asset.downloadAsync()', 'asset.downloadAsync' is undefined)`

**Comment by mobile-optimdata** [comment] 2017-07-31 13:14
@gamingumar Which version of `expo` so you use ?

**Comment by xavier-villelegier** [comment] 2017-07-31 13:15
@gamingumar Which version of expo do you use ?

**Comment by gamingumar** [comment] 2017-08-01 06:14
@xavier-villelegier i am using expo 19.0.0

**Comment by xavier-villelegier** [comment] 2017-08-01 12:10
@gamingumar The issue is more likely to come from `expo` than RNE, looking at https://github.com/expo/expo/issues/383.

Be sure to have the latest `expo` version and maybe try to ping them on the issue above ?

**Comment by nwkeeley** [comment] 2017-08-08 16:42
+1

**Comment by iRoachie** [comment] 2017-08-23 01:19
Closing this as non-actionable from our side guys.

**Closed by iRoachie** 2017-08-23 01:19 UTC
Labels: awaiting-reply, help wanted
