### ISSUE TITLE
Weird style using default button after upgrading to 1.0.0-beta7

### ISSUE THREAD

**Issue by fgagneten** [react-native-training/react-native-elements#1661] opened 2018-12-11 22:52 UTC
I have been working using React Native Elements version **0.18.4** Everything was OK

Today, I've upgraded to 1.0.0-beta7 (so I can try out themes and new features) but all the button got a weird style (see the image below):
![whatsapp image 2018-12-11 at 19 40 12](https://user-images.githubusercontent.com/14353978/49835344-a70a2780-fd7d-11e8-9c2a-9d01f434398b.jpeg)

Do you see the shadow and and the weird style of the button?

The code is the same as I had before (nothing changes):

    <Button
        raised
        icon={{ name: 'cached' }}
        key={1}
        title='BUTTON WITH ICON' />,
      <Button
       
        key={2}
      />,
      <Button
        raised
        containerViewStyle={ComponentsStyle.outlineLargeButton}
        large
        key={3}
        rounded
        borderRadius={35}
        color='#336688'
        outline
        title='example'
      />`

The problem started after upgrading the version of React Native Elements.

    react-native-cli: 2.0.1
    react-native: 0.57.7

Thanks

**Comment by xavier-villelegier** [comment] 2018-12-12 10:09
Hey @fgagneten 👋 
Thanks for taking the time to upgrade to 1.0.0-beta7 !

The API of the `Button` has changed a bit because it has been fully refactored, you can see the updated API [here](https://react-native-training.github.io/react-native-elements/docs/button.html).

The first things I see in your code:
* `borderRadius` and `color` doesn't exist anymore, you need to apply it through the styles
* `containerViewStyle` became `containerStyle`

Maybe you should use the repo with `next` branch directly because we added back a `type` props that can be `raised`, `outline` and `solid`. This will be in the next release, and we planned to write a migration guide from to `1.0.0`. Feel free to post some screens of your buttons before the update, and we can help you to get the good UI

**Comment by suihalee** [comment] 2018-12-16 08:36
I try this version and the background color of the button cannot be set too.
Let check that.

**Comment by OmbraDiFenice** [comment] 2018-12-16 17:11
I noticed the same weird style applied to buttons in my code, even if I used only `title` and `onPress` props:

```
<Button
    title="Login" 
    onPress={() => {
        // do stuff...
    }}
/>
```
result:
![image](https://user-images.githubusercontent.com/2358361/50056514-86ffad00-015d-11e9-99ed-b0a2d2516b0b.png)

Also, when I tap on the button, the "press shadow" visual cue that should be limited to the button boudaries goes out so it looks like I tapped on a generic area of the screen. Can the two things be connected?

**Comment by iRoachie** [comment] 2018-12-16 22:02
@OmbraDiFenice it's already been fixed on the `next` branch

**Comment by iRoachie** [comment] 2018-12-18 17:06
Duplicate of #1547

**Closed by iRoachie** 2018-12-18 17:06 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release
