### ISSUE TITLE
inputComponent

### ISSUE THREAD

**Issue by xepisode** [react-native-training/react-native-elements#1984] opened 2019-07-31 00:49 UTC
Hi,

i have been struggling on how to use picker inside input. is there any documentation or example available that i can refer to? 
been searching for it but no result that help me.

Thanks!

**Comment by Gregjarvez** [comment] 2019-07-31 17:30
@xepisode why exactly do you need a picker inside an input? Could you clarify your intentions a little bit more? Possibly provide a "half-made"  [expo](https://snack.expo.io/) example  Put comments at the place you intend to put a Picker

**Comment by iRoachie** [comment] 2019-08-02 02:36
Duplicate of https://github.com/react-native-training/react-native-elements/issues/1730

**Closed by iRoachie** 2019-08-02 02:36 UTC
Labels: ❔Question
