### ISSUE TITLE
Error after importing react-native-elements

### ISSUE THREAD

**Issue by newosetroc** [react-native-training/react-native-elements#329] opened 2017-04-21 23:13 UTC
Hi,

Would like to know if anyone has experienced error after importing react-native-elements? Would want to integrate it with my project but I cannot import it.

Having this error on my debugger
> Warning: Invalid argument supplied to oneOf, expected an instance of array.

installed react-native-elements using npm
> npm i react-native-elements --save

here is my package.json

 {
  "name": "AgentApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.2",
    "react-native-elements": "^0.11.1",
    "react-native-icons": "^0.7.1",
    "react-native-scrollable-tab-view": "^0.7.4",
    "react-native-stateless-form": "^0.2.2",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git"
  },
  "devDependencies": {
    "ImageViewer": "^1.5.7",
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
} 

Tried to import it to a component

> import { Button } from 'react-native-elements

But when I remove the react-native-elements import line my app works fine.

thanks!

**Comment by Monte9** [comment] 2017-04-22 03:41
@newosetroc 
> Would like to know if anyone has experienced an error after importing react-native-elements?
Several people are currently using RNE `v0.11.1` (including me) in their projects and this hasn't been an issue. 

With that being said, I would like to help you resolve this issue and figure out what's causing it. 

Alos you said it was an error on your debugger, although technically it's a Warning right (from what you posted above)? Is it causing the red screen of death? Or just a warning, and you can still use the Button component?

**Comment by dabit3** [comment] 2017-04-22 03:46
I just tested with 
```
"react-native": "0.43.4",
"react-native-elements": "^0.11.1",
```

And could not reproduce right now.

**Comment by madhutv** [comment] 2017-04-23 15:25
I have the same issue with: "dependencies": {
    "expo": "16.0.0",
    "react": "^16.0.0-alpha.6",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "^0.11.1",
    "react-native-router-flux": "^3.38.0",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0"
  }

**Comment by madhutv** [comment] 2017-04-23 15:27
Kinda think it might be something on ButtonGroup.js with innerBorderStyle: PropTypes.oneOf?

**Comment by sambanks** [comment] 2017-04-23 15:59
I have been having the same issue on a fresh expo install. Rolling back to 0.10.0 fixed it for me.

{
  "name": "firebase-auth",
  "version": "0.0.0",
  "description": "Hello Expo!",
  "author": null,
  "private": true,
  "main": "main.js",
  "dependencies": {
    "axios": "^0.16.1",
    "expo": "16.0.0",
    "firebase": "^3.8.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "0.10.0"
  }
}

**Comment by newosetroc** [comment] 2017-04-24 00:06
Downgraded to a lower version and now it working :)

>  "react-native-elements": "^0.9.7",

thanks all for the inputs :)

**Comment by Monte9** [comment] 2017-04-24 00:08
@newosetroc @sambanks @madhutv we are looking into this and will come up with a fix soon. Sorry about this. 😢

**Comment by newosetroc** [comment] 2017-04-24 00:13
@Monte9 No worries bro :).

@sambanks yup thats what I did.
@madhutv just downgrade to a lower version like what we did. Something to do with fresh repo install issue like @sambanks said.

**Comment by sambanks** [comment] 2017-04-24 00:33
Thanks @Monte9

**Comment by Monte9** [comment] 2017-04-24 03:26
OK, I created a new app with `expo v16` and `RNE v0.11.1` and it seems to be working fine. 
```
"dependencies": {
    "expo": "16.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "^0.11.1"
  }
```

It definitely throws a few warnings that you guys mentioned:
```
Warning: Invalid argument supplied to oneOf, expected an instance of array.
8:20:06 PM
Warning: Invalid argument supplied to oneOf, expected an instance of array.
8:20:06 PM
Warning: Invalid argument supplied to oneOf, expected an instance of array.
```

But these are non-critical warnings and shouldn't crash the app. Hence you should be able to use the latest version of this repo despite the warnings. 

For the full source code see this repo: https://github.com/react-native-training/react-native-elements-app

/cc @newosetroc @madhutv @sambanks thoughts?

**Comment by madhutv** [comment] 2017-04-24 05:20
@Monte9, Thank you for looking into this. I'm using the latest version and you are right, app dose not crash or anything.

**Comment by madhutv** [comment] 2017-04-26 00:10
Started using v0.11.2 and I don't get these warnings anymore.

**Comment by Monte9** [comment] 2017-04-26 02:08
@madhutv that's good to know! Closing this issue now.

**Closed by Monte9** 2017-04-26 02:08 UTC

**Comment by vineet-287** [comment] 2018-01-13 14:31
I am facing a strange error. In my office I am having ubuntu 1604 LTS configured and `RNE` seems to be working as expected. But when I configured the same app in `MAC` it seem not to be working. I've tried many ways to resolved that but nothing get fixed for me. I am using 

```
"dependencies": {
    "axios": "^0.17.1",
    "expo": "^22.0.2",
    "lodash": "^4.17.4",
    "name-initials": "^0.1.3",
    "prop-types": "^15.6.0",
    "react": "16.0.0-beta.5",
    "react-addons-update": "^15.6.2",
    "react-native": "^0.49.5",
    "react-native-drawer": "^2.5.0",
    "react-native-drawer-menu": "^0.2.4",
    "react-native-elements": "^0.18.5",
    "react-native-hr": "^1.1.3",
    "react-native-icon-button": "^1.0.0",
    "react-native-infinite-scroll-view": "^0.4.3",
    "react-native-largelist": "0.0.6",
    "react-native-loading-spinner-overlay": "^0.5.2",
    "react-native-modal-picker": "0.0.16",
    "react-native-orientation": "^3.1.3",
    "react-native-paginated-listview": "^1.0.2",
    "react-native-popup-menu": "^0.12.1",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.0.0-beta.19",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  }
```
in my package.json. Can anyone please suggest what I am missing ?

**Comment by iRoachie** [comment] 2018-01-14 00:49
Hey @vineet-287 can you create a new issue? Also it would be helpful if you have a link to the repo so that someone could at least attempt to help you.
