### ISSUE TITLE
Bad sizing for vertical sliders

### ISSUE THREAD

**Issue by matejcik** [react-native-training/react-native-elements#1281] opened 2018-06-25 12:48 UTC
**Explain what you did**

I am trying to build an application that has a slider on the left-hand side of the screen, and some descriptions in the rest of the space. I expect to do this through nesting two Views like this:

```jsx
<View style={{ flex: 1, flexDirection: "row", alignItems: "stretch" }}>
	<Slider orientation="vertical" />
	<View>
		<Text>hello world</Text>
		<Button title='Click me' onPress={function() {}} />
	</View>
</View>
```

**Expected behaviour**

If on the first view I leave the default flexDirection ("column"), and the Slider is horizontal, it takes up full width of the screen:
```
------O----
Hello world
[Click me]
```
I expect that when the slider is vertical, it will take up the full *height* of the screen:
```
|   Hello world
|
|   [Click me]
|
O
|
```

**Describe the bug**
The slider isn't visible at all.
When setting distinct background colors to the elements, the Slider element is completely missing.

**To Reproduce**
https://snack.expo.io/By8f7vRbQ

**Possible Solution**
It seems that sizing for the slider is messed up in several kinds of ways. For example, using a horizontal slider but not specifying its width (e.g., with flex layout and `alignItems: "center"`) will make the slider disappear completely.
(the native Slider will take up a minimum width)

AFAICT sizing works the same way for horizontal and vertical, so a vertical slider will reserve the (in)appropriate height, but zero width.
I tried to dive into the code and figure out how to change the sizing, but apparently the rotation is triggered by a CSS transform and I have no idea whatsoever how that works in regard to sizing.

**Comment by xavier-villelegier** [comment] 2018-06-29 11:28
@matejcik Thanks for reporting that, I agree that the slider styling is a bit messy and needs to be improved. Feel free to give it a shot if you have time.

**Comment by YeonV** [comment] 2018-12-22 12:15
The problem is, while being "vertical"-orientated, the slider still takes the same space in width.
So you can only make it work in a ugly-hacky way:
styles:
` 
 container: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between"
  },
wrapper: {
    alignItems: "center",
    flexDirection: "row",
    marginLeft: 10,
    width: 50,
    height: 180
  },
  slider: {
    flex: 1,
    flexBasis: 150,
    marginLeft: -52
  },`
Code:
`<View style={styles.container}>
       <View style={styles.wrapper}>
            <Slider
                orientation="vertical"
                minimumValue={0}
                maximumValue={127}
                style={styles.slider}
[...]
`
@xavier-villelegier While fixing this correctly, could you also add "vertical-reverse" as orientation?
Its a bit strange to have the minimum value at the top and the max value at the bottom.

**Comment by armenbadalyan** [comment] 2018-12-30 19:12
I've refactored the slider to use flexbox layout instead of `transform: [{ rotate: '90deg' }]` for orientation in #1698. This should improve vertical orientation behavior and make slider position and size more predictable. Please give it a try and let me know if it solves the issues above.

**Comment by Monte9** [comment] 2019-01-05 23:19
@armenbadalyan thanks for the PR! We'll review and let's get it merged into the v1 release!

**Closed** 2019-01-17 05:45 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release
