### ISSUE TITLE
Font Awesome icons are not loading

### ISSUE THREAD

**Issue by dmshikoff** [react-native-training/react-native-elements#1438] opened 2018-09-25 20:13 UTC
Im getting an error from Expo stating:

fontFamily 'FontAwesome' is not a system font and has not been loaded through Expo.Font.loadAsync

react-native-elements is the only package that I am using that uses Font Awesome. How do I fix this?

**Comment by iRoachie** [comment] 2018-09-28 03:37
Duplicate of #1005

**Closed by iRoachie** 2018-09-28 03:37 UTC
