### ISSUE TITLE
bug in Avatar component when there is rotateY

### ISSUE THREAD

**Issue by BatDroid** [react-native-training/react-native-elements#1796] opened 2019-02-21 13:14 UTC
**Explain what you did**
updating react-native-elements to a higher version of 1.0.0-beta5 & using avatar in a page.
with an action the page have many animation transforms (perspective,rotateY,scale,translateX).
the problem is when the rotate Y changes the image in avatar gets a bad shape

**To Reproduce**
using a version after  1.0.0-beta5  and putting the avatar in a component then trying to transforming with rotateY.

**Screenshots**
![screenshot_1550752329](https://user-images.githubusercontent.com/10198892/53171252-76edc900-35f7-11e9-8632-3ee9ab5678fa.png)
![screenshot_1550752326](https://user-images.githubusercontent.com/10198892/53171256-7a815000-35f7-11e9-898e-b6b9a9a68e57.png)

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.0.0     |
| react-native          |    0.56.0     |
| npm or yarn           |         |

**Comment by iRoachie** [comment] 2019-02-21 13:27
Can you create an example on https://snack.expo.io that reproduces this? I have no way to test this.

**Comment by BatDroid** [comment] 2019-02-21 18:09
> Can you create an example on https://snack.expo.io that reproduces this? I have no way to test this.

sure, here you are :)
https://snack.expo.io/@batreza/calm-candy

**Comment by iRoachie** [comment] 2019-02-24 13:28
In your example, the Avatar is transformed the same way as the View. I'm not seeing what the issue is. If you transform a parent View the children will be transformed as well.

**Comment by BatDroid** [comment] 2019-02-25 07:03
> In your example, the Avatar is transformed the same way as the View. I'm not seeing what the issue is. If you transform a parent View the children will be transformed as well.

in 1.0.0-beta5 there wasn't this issue, looked a bit in the source to see what brought this problem to the avatar component but couldn't find it. anyway i updated the [snack](https://snack.expo.io/@batreza/calm-candy) and added the react native `Image` and if you see it, it works as it should but the `Avatar` doesn't.

**Comment by BatDroid** [comment] 2019-06-12 14:00
any progress on this bug?

**Comment by iRoachie** [comment] 2019-10-03 05:26
This is fixed now in recent versions.

**Closed by iRoachie** 2019-10-03 05:26 UTC
Labels: :boom:  Bug, ✅ Fixed - Next Release
