### ISSUE TITLE
How to Align Text in header to the Left ?

### ISSUE THREAD

**Issue by aswinmohanme** [react-native-training/react-native-elements#441] opened 2017-06-21 10:59 UTC
The position of the text on the header is on the Center, how do I align that to the left, so that it's close to the left Icon.

Here is My Code:
  ```
  <Header
            leftComponent={<Icon name='menu'/>}
            centerComponent={<Text style={{fontFamily: 'karla', fontSize: 18}}>Tabi</Text>}
          />
```

I'm using the latest version of Elements on Android

**Comment by filiphosko** [comment] 2017-06-21 15:55
@aswinmohanme Hi, currently there is no simple way how to do it (like just passing a prop). The inner View positions the header elements horizontally using ```justifyContent: 'space-between'```. If you don't want to mess with it, you can get some results by either:

- wrapping you center element in a View and giving it some width, for example like this 
```jsx
<View style={{ width: Dimensions.get('window').width * 0.7 }}>
  <Text>Tabi</Text>
</View>
```
-  applying custom positioning for the center element, like this
```jsx
<Text style={{ position: 'relative', left: -(Dimensions.get('window').width * 0.3) }}>Tabi</Text>
```

Of course doing it like this is not awesome by any means, it should be much simpler. Since the center element is not centered in title bar on Android by default, I guess we should provide some simple way how to do it.

**Comment by aswinmohanme** [comment] 2017-06-22 04:28
Tried the First one, and it worked ! Thanks.

Should I keep the issue open or close it ?

**Comment by filiphosko** [comment] 2017-06-22 18:45
We can leave it open for now, I'll close it later.

**Comment by AudyOdi** [comment] 2017-11-06 02:13
Hey @Monte9, I would like to try fixing this issue. After digging through `header` source code, I realize that `innerContainer` uses `justifyContent: 'space-between'` to make the title at the center of the header. One way I can think of to make the title align to the left is we can add a container (`View`) that wrap the `Text` component (at `header/Title.js`) and use `flex: 1, alignItems: 'flex-start'` as the default container style. We can also use `Platform` to position it at center if it's iOS, and position it at left if it's Android as the default. Please let me know about what you think about this idea, I'm also open for any suggestion. Thanks!

**Comment by Monte9** [comment] 2017-11-06 03:08
Great @AudyOdi! Yeah, that makes sense to me. 

> We can also use Platform to position it at center if it's iOS and position it at left if it's Android as the default.
Yeah, that would def be an improvement to Header component. 👍

**Comment by AudyOdi** [comment] 2017-11-06 03:20
@Monte9 Awesome! I will make the PR soon! 👍

**Comment by AudyOdi** [comment] 2017-11-07 14:28
@Monte9 I manage to update the `Header` and `Title` component, also update the tests, but I got stuck in error `Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules` when trying to run the tests (This is applied to all tests). I think this is caused by importing `NativeModule` which is unavailable in jest. But, after I looked at it, it referred to `URL.js` from `example/node_modules/react-native/Libraries/Blob/URL.js`. It gives me the same error when I'm on the master branch. I have searched through the internet, but can't really find any solution. Do you know how to fix this?

**Comment by iRoachie** [comment] 2018-02-28 13:39
Added in https://github.com/react-native-training/react-native-elements/pull/946. Will be apart of the `1.0.0-beta3` release

**Comment by AudyOdi** [comment] 2018-02-28 14:25
hi @Monte9, sorry I got carried away with work since I faced the problem. I actually tried it again a couple of weeks ago, but still got the error (different one, but still related to other test files). Thanks to @iRoachie making PR for this improvement! Will try to fix other issues 👍

**Comment by iRoachie** [comment] 2018-03-11 18:13
Live in [1.0.0-beta3](https://github.com/react-native-training/react-native-elements/releases/tag/v1.0.0-beta3)

**Closed by iRoachie** 2018-03-11 18:13 UTC
Labels: Enhancement, Fixed - Next Release
