### ISSUE TITLE
Q: avatar positioning

### ISSUE THREAD

**Issue by sigmazen** [react-native-training/react-native-elements#249] opened 2017-03-25 15:01 UTC
Hi  
I'm trying to figure out how to follow the same `flex` logic as my text and image examples.  
The code is below and I'm using  `{/* ... */}`  to comment out the various sections for demo purposes.
Uncommenting `Text`  and commenting `Image` and `Avatar`  positions the text correctly.  
The correct positioning also occurs for `Image`.  
However, when I then try `Avatar` it messes up - the top_parent is no longer center-center  and the bottom-parent falls off the bottom-right.  
I've managed to get around this by using the `containerStyle` prop with _manual_ overrides, but is there an easier way to handle this rather than figuring out the `margin` values?
Should I be adding a negative-offset based on the height and width of the avatar itself ?  
Thanks in advance

    import React, { Component } from 'react';
    import { StyleSheet, ScrollView, Image, View } from 'react-native'
    import { Grid, Col, Text, Row, Button, CheckBox } from 'react-native-elements';
    import Avatar from 'react-native-elements/src/avatar/Avatar';
    import StewieSml from '../components/images/stewie_sml.jpg';
    
    const ProfileScreen = ({ navigation }) => {
    
        return (
          <View style={styles.container}>
            <View style={styles.top_parent}>
    {/*          <Text>Center-Center</Text>       */}
    {/*          <Image source={StewieSml} />     */} 
              <Avatar medium rounded title="SM" activeOpacity={0.7} 
                containerStyle={{marginBottom: 30, marginRight: 30}} />      
            </View>
            <View style={styles.bottom_parent}>
    {/*          <Text>Bottom-Right</Text>        */} 
    {/*          <Image source={StewieSml} />     */} 
              <Avatar medium rounded title="SM" activeOpacity={0.7} 
                containerStyle={{marginBottom: 30, marginRight: 40}} />     
            </View>
          </View> 
    
        )
    };
    
    const styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: 'whitesmoke',
      },
      top_parent: {
        flex: 2,
        alignItems: 'center',       //left-right if flexDirection is column
        justifyContent: 'center',   //top-bottom if flexDirection is column
        borderStyle: 'solid',
        borderColor: '#AAAAAA',
        borderWidth: 10,
      },
      bottom_parent: {
        flex: 4,
        alignItems: 'flex-end',     //left-right if flexDirection is column
        justifyContent: 'flex-end', //top-bottom if flexDirection is column
        borderStyle: 'solid',
        borderColor: '#BBBBBB',
        borderWidth: 10,
      },
    })
    export default ProfileScreen;

**Comment by Monte9** [comment] 2017-04-12 08:29
Snack demo here: https://snack.expo.io/ByOuIeGTg

**Comment by Monte9** [comment] 2017-04-12 08:30
@sigmazen I am not sure I totally understand what the problem is. Can you briefly explain it again? Also feel free to change the snack example above to demonstrate the bug.

**Comment by kdenz** [comment] 2017-04-17 17:22
@Monte9  Hi, why is it so difficult to make avatar correctly center?
Without using margin-bottom and margin-right to avatar's style, it just overlaps with elements before and after it. Now this makes it hard to perfectly center at a number of different devices with different screen sizes. 

Bug here:
https://snack.expo.io/HyLNKOGAe

**Comment by binoy14** [comment] 2017-05-10 15:55
Closing in favor of #359

**Closed by binoy14** 2017-05-10 15:55 UTC
