### ISSUE TITLE
List "badge" causes title text to not align with other elements

### ISSUE THREAD

**Issue by henrynw** [react-native-training/react-native-elements#547] opened 2017-08-09 15:33 UTC
If you create a list with multiple list items, some of which contain badges and others which do not, the titles of the items with badges will not align with the items that do not have badges.

Example below:

![screen shot 2017-08-09 at 8 33 09 am](https://user-images.githubusercontent.com/461928/29129999-699993da-7cdd-11e7-8fc9-020a02f51a3a.png)

**Comment by Monte9** [comment] 2017-08-13 23:29
Hmm.. that's caused by flex. Will need to look into it a bit more to figure out what the best way to handle that is.

In the meantime, did you happen to find any good solution to fix it @henrynw? Also your app looks good, mind showing us a bit more of it? I'd love to see how you are using RNE in your app. 😉

**Comment by iRoachie** [comment] 2017-11-03 10:02
Fixed in v18.0.0

**Closed by iRoachie** 2017-11-03 10:02 UTC
Labels: bug, Fixed - Next Release, good first issue
