### ISSUE TITLE
"x" button does not clear text

### ISSUE THREAD

**Issue by chetanparakh** [react-native-training/react-native-elements#1365] opened 2018-08-12 18:19 UTC
For some reason the "x" button does not clear text when platform attribute is not set.
On adding platform="ios" or platform="android" the x button on the right side of the search bar clears the text.

```
<SearchBar
     light
     inputContainerStyle={{margin:0, backgroundColor:"#E0E0E0"}}
     containerStyle={{width:"100%", backgroundColor:"white", paddingTop:0, paddingBottom:0, paddingLeft:0, borderTopWidth:0, borderBottomWidth:0}}
      onChangeText={(text)=>this.setState({searchText: text})}
      icon={{ type: 'font-awesome', name: 'search' }}
      placeholder='Search ...'
      onSubmitEditing={() => this.submitButtonClicked()}
      returnKeyType='search'
      enablesReturnKeyAutomatically= {!this.state.searchText!=""}
      onCancel={()=> this.props.navigation.pop()}
      autoFocus={true}
   />
```

![image](https://user-images.githubusercontent.com/18354984/44005047-c352d6d2-9e3a-11e8-8e42-0544ec74e354.png)

**Comment by xavier-villelegier** [comment] 2018-08-12 20:57
Duplicate of #1064

**Closed by xavier-villelegier** 2018-08-12 20:57 UTC
