### ISSUE TITLE
I got one problem when i initial elements on index.android.js

### ISSUE THREAD

**Issue by hashemirafsan** [react-native-training/react-native-elements#398] opened 2017-05-27 14:23 UTC
/Users/rafsan/Projects/android/chatters/node_modules/react-native-elements/src/rating/images/heart.png: Unexpected character '�' (1:0)

can any one help me out ?

**Comment by nguyendhse** [comment] 2017-05-27 15:18
Do you try to stop server and run `npm start` or `yarn start` ?

**Comment by hashemirafsan** [comment] 2017-05-27 16:25
yeah

**Comment by filiphosko** [comment] 2017-05-30 14:02
Hi, I tested it and I can't reproduce your issue. This is usually a packager problem, it can happen when the packager server is running and you add some image asset to your project. Do you still have this issue?

**Comment by binoy14** [comment] 2017-06-02 15:42
Closing this as it can't be reproduced. Feel free to ask for help if you still having this issue

**Closed by binoy14** 2017-06-02 15:42 UTC
