### ISSUE TITLE
Overlay "fullscreen" prop doesnt do fullscreen

### ISSUE THREAD

**Issue by The-Code-Monkey** [react-native-training/react-native-elements#1372] opened 2018-08-16 12:45 UTC
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
What you were trying to accomplish.

A full screen Overlay/Modal from inside a bar top of the page that is only 150 tall,
I did fullscreen and it just takes up the width and the height of the parent not of the device like the docs say.

**Expected behaviour**

it should open the overlay/modal full width of the device with the grey touchable background behind it.

**Describe the bug**

docs are wrong

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

https://snack.expo.io/HJAFWemI7

**Possible Solution**
Can you suggest a possible fix that would address this issue?

possibly something like how bootstrap renders its modals even if its placed in the middle of content it will display it full screen.

**Screenshots**

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | v1.0.0-beta5
| react-native | v0.56.0
| npm or yarn | npm v6.1.0

**Comment by iRoachie** [comment] 2018-08-16 13:05
Here's a snack taking up the full width and height. https://snack.expo.io/Sy8YUlQLm. What do you mean?

**Comment by The-Code-Monkey** [comment] 2018-08-16 13:14
I had it quite deep within a position absolute component which in turn had a few other componenets around it including buttons and scrollviews, when i called it the item only went to the width and height of the position absolute component that was 100% width and 150 height.

**Comment by iRoachie** [comment] 2018-08-16 13:15
Can you reproduce this in a snack?

**Comment by The-Code-Monkey** [comment] 2018-08-16 13:34
not sure as a lot of the stuff im doing is for a nda client so i don't think so sorry. wish i could.

**Comment by iRoachie** [comment] 2018-08-16 13:46
Closing as not able to reproduce.

**Closed by iRoachie** 2018-08-16 13:46 UTC
Labels: ⏳Awaiting Reply, 🔦 Help Wanted
