### ISSUE TITLE
Overlay onBackdropPress not working with Android device.

### ISSUE THREAD

**Issue by foloinfo** [react-native-training/react-native-elements#1285] opened 2018-06-28 03:50 UTC
**Explain what you did**
Using Overlay component with `onBackdropPress` prop in Android device.

**Expected behaviour**
function to be called.

**Describe the bug**
function is not called.

**To Reproduce**
Use Overlay component and tap overlay background.

**Possible Solution**
> moving position: 'absolute' style to TouchableOpacity from child View component
> https://github.com/facebook/react-native/issues/4878#issuecomment-183864743

may solve this problem.

**Your Environment (please complete the following information):**

| software | version |
| -- | -- |
| react-native-elements | 1.0.0-beta5|
| react-native |0.55.2 |
| yarn |1.5.1|

**Comment by iRoachie** [comment] 2018-07-05 04:51
Unable to replicate this, seems to be working fine https://snack.expo.io/HySJE7sMQ

**Comment by xavier-villelegier** [comment] 2018-07-28 15:43
Closing this because we can't reproduce it and I can't find others having this issue. Feel free to ping me if anyone encounters this again

**Closed by xavier-villelegier** 2018-07-28 15:43 UTC
Labels: ⏳Awaiting Reply, 🔦 Help Wanted

**Comment by StijnCoolen** [comment] 2019-02-11 12:14
@iRoachie @xavier-villelegier It seems to happen when you add `postion: 'absolute'` to the `overlayStyle` prop.

**Comment by devonwesley** [comment] 2019-09-10 01:25
@foloinfo How you get this to work?

**Comment by iRoachie** [comment] 2019-09-10 01:35
@devonwesley here's an example
https://snack.expo.io/@roach_iam/lonely-cookies

![Kapture 2019-09-09 at 21 34 58](https://user-images.githubusercontent.com/5962998/64577230-c4d6de00-d349-11e9-8baa-0fe071bc1fc2.gif)

**Comment by devonwesley** [comment] 2019-09-10 02:06
I figured it out. Overlay is a modal. I had it wrapped around another modal and the contents inside of the child modal, where being covered or blocked, not sure. 

But don't use "Overlay" with Modals because it is a Modal.
