### ISSUE TITLE
Form container border bottom on Android 

### ISSUE THREAD

**Issue by tasharofi** [react-native-training/react-native-elements#213] opened 2017-03-09 06:11 UTC
Hi all, 

I am having problem changing the bottom border of the input container on Android (Working fine on iOS). When I set the style to following into containerStyle
{
    borderBottomColor: 'red'
}

this is what I get 

![screen shot 2017-03-09 at 4 59 20 pm](https://cloud.githubusercontent.com/assets/23203341/23738108/399755d8-04eb-11e7-858c-e43fea4ca2af.png)

and the following 
{
    borderWidth: 1,
    borderBottomColor: 'red'
}

gives me

![screen shot 2017-03-09 at 5 08 24 pm](https://cloud.githubusercontent.com/assets/23203341/23738128/4ada4dbe-04eb-11e7-9af8-d3d38031a7c1.png)

Just to note my first style which is only setting the borderbottomColor works fine on iOS.

Thanks,

**Comment by binoy14** [comment] 2017-03-15 21:06
@tasharofi To clarify, Are you trying to change the color of the line under the input? or that when you set `borderWidth` and `borderBottomColor` the expectations are different on android and ios?

**Comment by mattijauhiainen** [comment] 2017-03-30 08:29
Had the same issue. Seems like the underline color is defined as style for iOS and and as a prop for Android. So the trick is to pass the color as a android specific prop like this:
```
<FormInput
   ...yourOtherProps
   underlineColorAndroid="#ff0000"
/>
```

**Comment by binoy14** [comment] 2017-03-30 08:46
@mattijaunhiainen if you have the solution, feel free to send a PR, we will review it.

**Comment by tasharofi** [comment] 2017-03-30 08:51
@mattijauhiainen @binoy14 sorry for the delayed response. Yes your solution is the right one and it resolves my problem.

**Comment by DavidKongDesheng** [comment] 2017-04-10 07:05
Any updates on this issue?

**Comment by binoy14** [comment] 2017-04-10 21:58
@tasharofi @mattijauhiainen If we add a prop on FormInput `underlineColor` and make sure it is applied both on android and ios does that make it easier? I am still not 100% sure about what the issue is so if someone can make a [snack](https://snack.expo.io/) it would be a great help.

**Comment by Monte9** [comment] 2017-04-10 22:05
@binoy14 everytime someone mentions `snack`, it makes me hungry. Is that the intended effect? 🤔

**Comment by tasharofi** [comment] 2017-04-11 01:15
@binoy14 The initial problem was the inconsistency between ios and android when it comes to setting the border bottom color. I had issues with the following style behaving strangely on android 

{
borderWidth: 1,
borderBottomColor: 'red'
}

but then realised by simply setting the underlineColorAndroid I can get what I want. Just to let you know that this property is already supported and can be set so no need to do any change. 

@DavidKongDesheng I believe you have problems setting the border bottom color on Android, in that case underlineColorAndroid="#ff0000" should resolve your problem.

**Comment by Monte9** [comment] 2017-04-11 03:06
Thanks for the solution @tasharofi. 

Let me know if this works for you @DavidKongDesheng and we can close this issue.

**Comment by DavidKongDesheng** [comment] 2017-04-11 05:57
Thanks @Monte9  @tasharofi, works fine me.

**Closed** 2017-04-11 06:39 UTC
Labels: bug

**Comment by illu9000** [comment] 2017-11-28 20:49
underlineColorAndroid="transparent" work fine 

rn 0.48
android 5.1

**Comment by Morriz** [comment] 2018-12-17 19:46
Why is this closed? Isn't it showing a discrepancy between handling in ios & android? Also, setting that prop draws a line too high and input text renders right through it...
