### ISSUE TITLE
Problem with sizing of Avatar component

### ISSUE THREAD

**Issue by boyombo** [react-native-training/react-native-elements#1199] opened 2018-05-16 16:17 UTC
### Description

1. Explain what you did
       I used the Avatar component by copying and pasting from example code into a react-native app I created
2. What you expected to happen
       That when the size attribute is set to "medium" or "large", the size of the avatar would increase as             shown in the examples
3. What actually happens
      All the avatars were of the same size, "small"

Also please include the version of `react-native-elements` that you are using.  
     VERSION " react-native-elements@^0.19.1

### Reproduction Steps and Sample Code

We highly recommend that you try to reproduce your bug on https://snack.expo.io/ and provide a link.
https://snack.expo.io/@boyombo/avatar-size

If you can't reproduce the bug on Snack, provide an example of your code and briefly explain what the code is suppose to be doing.

### Solution

Can you suggest a possible fix that would address this issue? Ideally, you should be able to submit a PR to fix it. See our [contributing guide](./CONTRIBUTING.md) for more details.

**Comment by xavier-villelegier** [comment] 2018-05-16 16:19
@boyombo I think it's duplicate of #1192

**Comment by xavier-villelegier** [comment] 2018-05-16 16:29
Haha no problem  💪 Glad you fixed it 👍

**Closed by xavier-villelegier** 2018-05-16 16:29 UTC
Labels: ⏳Awaiting Reply, 🔦 Help Wanted

**Comment by boyombo** [comment] 2018-05-16 16:36
I think the docs should probably point this out, maybe I submit a PR?

**Comment by xavier-villelegier** [comment] 2018-05-16 16:41
@boyombo This is already the case. You can check the versioned docs [here](https://react-native-training.github.io/react-native-elements/versions.html), so you have the [`0.19.0` Avatar](https://react-native-training.github.io/react-native-elements/docs/0.19.0/avatar.html#props) and [`1.0.0-beta5` Avatar](https://react-native-training.github.io/react-native-elements/docs/avatar.html#size) 😄

**Comment by iRoachie** [comment] 2018-05-16 16:44
We could make it a bit clearer by https://github.com/react-native-training/react-native-elements/issues/1201. Also will implement the new issue templates
