### ISSUE TITLE
can't change Slider thumb with icon or image.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-training/react-native-elements#1641] opened 2018-12-05 10:31 UTC
*Explain what you did**
Step 1 :- Vector icon support for the thumb in Slider.

**Expected behaviour**

Thumb Image Should be changed

**Describe the bug**

I have used React-native -element Slider and i want to change thumb image but it is not possible.

**Possible Solution**

Add thumb Image Option (Props)

![ex](https://user-images.githubusercontent.com/30401136/49515666-93fae180-f8bd-11e8-9646-2130bd45fdf6.png)

**Comment by iRoachie** [comment] 2018-12-06 00:19
Duplicate of #1394

**Closed by iRoachie** 2018-12-06 00:19 UTC

**Comment by Biplovkumar** [comment] 2018-12-06 05:57
Okay thanks @iRoachie .
