### ISSUE TITLE
add prefix to a long text

### ISSUE THREAD

**Issue by menesh2** [react-native-training/react-native-elements#2020] opened 2019-08-15 14:21 UTC
> Before filling out an issue, be sure to check the version of react-native-elements you are using and the docs for that version over [here](https://react-native-training.github.io/react-native-elements/versions.html).

**Explain what you did**
on ios/android
write text that is longer than the searchBar's width,
take the marker to the beginning of the text
now insert new letter

**Expected behaviour**
i can see the new letter

**Describe the bug**
the new letter is not displayed and to see it i need to go left

**To Reproduce**
We highly recommend that you re-create the bug on [Snack](https://snack.expo.io). If not, list the steps that a reviewer can take to reproduce the behaviour:

# Steps
on ios/android
1. write text that is longer than the searchBar's width,
2. take the marker to the beginning of the text
3.insert new letter

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements | .  ^1.1.0         |
| react-native          |    0.59.5     |
| npm or yarn           |    6.7.0     |

**Comment by iRoachie** [comment] 2019-08-16 12:24
Can you create an example on https://snack.expo.io that reproduces this?

**Comment by menesh2** [comment] 2019-08-18 06:29
yep [click here](https://snack.expo.io/r1ajk_8NS)
hope this is good enough

**Comment by iRoachie** [comment] 2019-09-01 22:58
Seems to be an upstream bug, the same thing happens for native TextInput https://snack.expo.io/@roach_iam/textinput-bug

**Comment by menesh2** [comment] 2019-09-05 08:49
you are right, it does happen on text input, thanks.

**Comment by iRoachie** [comment] 2019-09-05 13:26
Closing as not actionable

**Closed by iRoachie** 2019-09-05 13:26 UTC
Labels: :boom:  Bug, Upstream
