### ISSUE TITLE
Grid 'hiding' elements?

### ISSUE THREAD

**Issue by dgdosen** [react-native-training/react-native-elements#300] opened 2017-04-14 06:04 UTC
I'm trying to use a grid to position react native components side by side (FormLabels).   If I don't use a grid, I can see that content.   

However, If I place those FormLabels in a Grid Column, they don't show up on in my ux.  Should that be the case?

As part of my render:

```
        <Grid>
          <Col>
            <FormLabel>Target Likelihood:</FormLabel>
          </Col>
          <Col>
            <FormLabel>{this.state.value}</FormLabel>
          </Col>
        </Grid>
```

Should form labels be viewable in a grid?

**Comment by renehauck** [comment] 2017-04-17 13:47
same here with icons:

```
//icon invisible
 <Grid>
      <Col >
          <Icon name='home'  color='red'/>
      </Col>
 </Grid>


//icon visible
<Icon name='home'  color='red'/>
```

**Comment by nimishrocks** [comment] 2017-05-13 13:54
Same here with Text component of 'react-native-elements'
```
<Grid>
           <Col><Text>Something</Text></Col>
           <Col><Text>Is fishy</Text></Col>
 </Grid>
```
But 
```
<Text>Something</Text>
Text>Is fishy</Text>
```
is working.
Any solution?

**Comment by nimishrocks** [comment] 2017-05-13 14:46
Problem solved , wrap the grid with the view component of the react-native and set the style of the view with flex:1
```
<Grid>
           <Col><Text>Something</Text></Col>
           <Col><Text>Is fishy</Text></Col>
 </Grid>
```

**Comment by binoy14** [comment] 2017-05-14 04:26
@dgdosen @renehauck @nimishrocks Check this snack demo.I can't seem to reproduce it. https://snack.expo.io/B1RHnLHx-

**Comment by dcordz** [comment] 2017-05-19 03:32
I was having this issue as well, turns out I hadn't changed the style props on each grid component (Grid, Row, Col) to containerStyle after upgrading from 0.9.7 to 0.12.2.

https://react-native-training.github.io/react-native-elements/API/grid/#gridcomponent-props

**Comment by binoy14** [comment] 2017-05-19 04:33
@dcordz Thanks for pointing it out. Closing this since it's not reproducible. Feel free to reach out if your still having an issue

**Closed by binoy14** 2017-05-19 04:33 UTC
