### ISSUE TITLE
error: fontFamily 'Material Icons' is not a system font - react 0.43/expo 16

### ISSUE THREAD

**Issue by marstall** [react-native-training/react-native-elements#333] opened 2017-04-23 20:33 UTC
After I upgraded to react-native 0.43 and expo 16 (so i could use FlatList), I started consistently getting the following error whenever I include a React-Native Elements tag: "console.error: 'fontFamily 'Material Icons' is not a system font has not been loaded through Exponent.Font.loadAsync'"

Here's my package.json:

{
  "name": "reflyer-mobile",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "jest-expo": "^0.3.0",
    "react-native-scripts": "0.0.25",
    "react-test-renderer": "~15.4.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^16.0.0",
    "mobx": "3.1.7",
    "mobx-promise": "^0.3.1",
    "mobx-react": "^4.1.5",
    "mobx-utils": "^2.0.1",
    "react": "16.0.0-alpha.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz",
    "react-native-elements": "^0.10.2",
    "react-native-foursquare-api": "0.0.4",
    "react-native-vector-icons": "^4.0.1",
    "react-navigation": "git+https://github.com/react-community/react-navigation.git",
    "styled-components": "^1.4.4"
  }
}

Any ideas? Thanks!

**Comment by marstall** [comment] 2017-04-23 20:39
I just noticed that when I dismiss the error (which has a red background) I actually see the page rendered, but with ? icons substituted for the chevrons in my ListItems and the magnifying glass in my search bar. Thanks again! Loving React Native Elements.

**Comment by marstall** [comment] 2017-04-23 21:27
hm this is also happening with FontAwesome in react-native-vector-icons so I opened a ticket with expo instead https://forums.expo.io/t/font-trouble-with-expo-16/436/1

**Comment by Monte9** [comment] 2017-04-23 22:28
@marstall I appreciate the follow-up updates. Do they recommend posting on the forum now? I would recommend creating an issue on here too for greater visibility.

https://github.com/expo/expo-sdk/issues

Also I am closing this issue now as it's more relevant on the expo repo as you pointed out. Feel free to open if the issue occurs originates from RNE.

**Closed by Monte9** 2017-04-23 22:28 UTC

**Comment by alien3d** [comment] 2017-04-29 13:05
not related to expo or react native element.. just hit this bug..  is the react-native link react-native-vector-icon..   Seem effect ios only ..Android no issue.

**Comment by developdeez** [comment] 2017-08-13 23:56
same issue

**Comment by SuperAL** [comment] 2017-12-19 02:42
Check this issue: [Getting "not a system font" error despite using Font.loadAsync](https://github.com/expo/expo-sdk/issues/55)
You may find solution there.

**Comment by gokulkulkarni1987** [comment] 2018-04-03 06:44
getting same issue, any solution found?

**Comment by xavier-villelegier** [comment] 2018-04-03 08:16
@gokulkulkarni1987 Check out https://github.com/react-native-training/react-native-elements/issues/620#issuecomment-355530210, maybe it can help

**Comment by gokulkulkarni1987** [comment] 2018-04-07 04:35
@xavier-villelegier I tried that multiple times, still no help

**Comment by TheSalarKhan** [comment] 2018-05-09 19:11
Hi people! I had the exact issue. Did all and nothing worked, and then I tried this article. I made the AppFontLoader component and nested my main view inside it, now it all works fine: 

https://javascriptrambling.blogspot.com/2018/03/expo-icon-fonts-with-react-native-and.html

All thanks to this article! 👍

**Comment by wesleyfc** [comment] 2018-07-19 06:42
I experienced the same issue. What i realized is the react-native-vector-icons component calls the fontFamily as "Material Design Icons" instead of MaterialCommunityIcons... what i had to do to fix the issue is on the Font.loadAsync method explicit the font name.
Something like this:


    await Font.loadAsync({
      Roboto: require("native-base/Fonts/Roboto.ttf"),
      FontAwesome: require("native-base/Fonts/FontAwesome.ttf"),
      Roboto_medium: require("native-base/Fonts/Roboto_medium.ttf"),
      Ionicons: require("@expo/vector-icons/fonts/Ionicons.ttf"),
    });

    **await Font.loadAsync("Material Design Icons", require("native-base/Fonts//MaterialCommunityIcons.ttf"));**

**Comment by NextStepDev** [comment] 2018-08-01 22:38
To get around this I had to change a line of code in ./node_modules/react-native-elements/src/list/ListItem.js

On line 15 change:

`import Icon from '../icons/Icon';`

To this:

`import Icon from '@expo/vector-icons/MaterialIcons';`
