### ISSUE TITLE
Searchable Dropdown Flatlist in an Overlay

### ISSUE THREAD

**Issue by ayushagarwalk** [react-native-training/react-native-elements#2055] opened 2019-09-07 05:31 UTC
**Is your feature request related to a problem? Please Describe.**
I could not find a dropdown list component in react native element UI Kit.. 
**Describe the solution you'd like**
I Got an Image as an Example please have a look into it.. It a UI component which is Searchable and a List of items is displayed in Overlay like a dropdown
Image Example: [1] https://imgur.com/9G3jU9V

**Additional context**
Thank you for Such a wonderful UI Components Lib <3

**Comment by iRoachie** [comment] 2019-10-03 06:04
Duplicate of #253

**Closed by iRoachie** 2019-10-03 06:04 UTC
