### ISSUE TITLE
My app crashed  in Android emulator 7.0

### ISSUE THREAD

**Issue by xubuhang** [react-native-training/react-native-elements#340] opened 2017-04-26 03:06 UTC
### Description

1. Explain what you did
My project is a standard React Native project created using `react-native init`.
, then follow these installation instructions:
`npm i react-native-vector-icons --save && react-native link react-native-vector-icons`
`npm i react-native-elements --save`.
Lastly,I used  `react-native run-android`.

2. What you expected to happen
Android emulator should display normal view.

3. What actually happens
However,My app crashed。(but my real phone  is ok)
Also please include the version of `react-native-elements` that you are using.
react-native 0.43
react-native-elements 0.11.2
react 16.0.0-alpha.6
Android emulator android 7.0
Real phone android 5.1.1
        
### Reproduction Steps and Sample Code
`04-26 11:04:47.895 6702-6747/com.hms I/OpenGLRenderer: Initialized EGL, version 1.4
04-26 11:04:47.895 6702-6747/com.hms D/OpenGLRenderer: Swap behavior 1
04-26 11:04:47.899 6702-6747/com.hms W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-26 11:04:47.899 6702-6747/com.hms D/OpenGLRenderer: Swap behavior 0
04-26 11:04:48.051 6702-6747/com.hms E/gralloc_ranchu: gralloc_register_buffer(0xdb30bc20): invalid buffer
04-26 11:04:48.051 6702-6747/com.hms W/GraphicBufferMapper: registerBuffer(0xdb30bc20) failed -22 (Invalid argument)
04-26 11:04:48.051 6702-6747/com.hms E/GraphicBuffer: unflatten: registerBuffer failed: Invalid argument (-22)
04-26 11:04:48.051 6702-6747/com.hms E/Surface: dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -22
04-26 11:04:48.052 6702-6747/com.hms E/EGL_emulation: tid 6747: init(324): error 0x3003 (EGL_BAD_ALLOC)
04-26 11:04:48.052 6702-6747/com.hms E/EGL_emulation: tid 6747: eglCreateWindowSurface(847): error 0x3003 (EGL_BAD_ALLOC)
04-26 11:04:48.055 6702-6747/com.hms A/OpenGLRenderer: Failed to create EGLSurface for window 0xdb3d8508, eglErr = EGL_BAD_ALLOC
                                                       
                                                       --------- beginning of crash
04-26 11:04:48.055 6702-6747/com.hms A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6747 (RenderThread)
                                             
                                             [ 04-26 11:04:48.057  1259: 1259 W/         ]
                                             debuggerd: handling request: pid=6702 uid=10097 gid=10097 tid=6747`

**Comment by tarang9211** [comment] 2017-04-26 08:08
Hey @xubuhang I tried reproducing this issue and wasn't able to. I even tried the iOS version and that seemed to work fine, on my device as well as the simulator.

**Comment by bozzmob** [comment] 2017-05-04 04:55
Hi @xubuhang , I can confirm that I am not able to reproduce the issue. Followed your commands. Maybe, there was some other issue with the environment. Were you able to make progress?

**Comment by binoy14** [comment] 2017-05-04 12:18
Closing this since it's not reproducible. Feel free to open it if needed

**Closed** 2017-05-04 12:18 UTC
Labels: Needs Response from Author

**Comment by mike-aungsan** [comment] 2017-08-05 00:51
I am having the same issue on Android 7 ZTE - Z971

**Comment by Monte9** [comment] 2017-08-08 07:56
> However,My app crashed。(but my real phone is ok)

@mike-aungsan since this is android emulator specific, I'd recommend just running it on a real device.

**Comment by dunnleaddress** [comment] 2018-08-20 17:13
There is a post https://teamtreehouse.com/community/my-screen-is-completely-blank-and-no-noticeable-error-in-logs

I agree with (Steffy Joseph on May 19, 2016)

Check it out.
